import * as dotenv from 'dotenv';
dotenv.config();

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const foundationLessons = [
  // ── Lesson 1: Greetings & Politeness ──────────────────────────────────────
  {
    level: 'A1' as const,
    theme: 'foundation-greetings',
    is_premium: false,
    content_json: {
      title: { fr: 'Salutations et politesse', en: 'Greetings & Politeness' },
      description: {
        fr: 'Apprenez les 12 mots essentiels pour saluer et etre poli en anglais.',
        en: 'Learn the 12 essential words for greeting people and being polite in English.',
      },
      emoji: '👋',
      duration: 10,
      xpReward: 25,
      vocabulary: ['hello', 'goodbye', 'good morning', 'good night', 'hi', 'bye', 'welcome', 'please', 'thank you', 'sorry', 'excuse me', "you're welcome"],
      exercises: [
        {
          type: 'mcq',
          question: 'How do you say "bonjour" in English?',
          questionFr: 'Comment dit-on "bonjour" en anglais ?',
          options: ['Goodbye', 'Hello', 'Sorry', 'Welcome'],
          correctIndex: 1,
          explanation: '"Hello" /həˈloʊ/ is the most common greeting. You can use it any time of the day.',
          explanationFr: '"Hello" /həˈloʊ/ est la salutation la plus courante. On peut l\'utiliser a tout moment de la journee.',
        },
        {
          type: 'mcq',
          question: 'What is the difference between "hi" and "hello"?',
          questionFr: 'Quelle est la difference entre "hi" et "hello" ?',
          options: [
            '"Hi" is more informal than "hello"',
            '"Hi" is more formal than "hello"',
            'They mean different things',
            '"Hi" is only used at night',
          ],
          correctIndex: 0,
          explanation: '"Hi" /haɪ/ is informal (like "salut"), while "hello" is more neutral and works in any situation.',
          explanationFr: '"Hi" /haɪ/ est informel (comme "salut"), alors que "hello" est plus neutre et fonctionne dans toutes les situations.',
        },
        {
          type: 'fill',
          sentence: 'Can I have some water, ___ ?',
          sentenceFr: 'Puis-je avoir de l\'eau, ___ ?',
          answer: 'please',
          options: ['please', 'sorry', 'hello', 'goodbye'],
          explanation: '"Please" /pliːz/ is used to make a polite request. Always add it when asking for something!',
          explanationFr: '"Please" /pliːz/ rend une demande polie. Ajoutez-le toujours quand vous demandez quelque chose !',
        },
        {
          type: 'mcq',
          question: 'Someone helps you carry your bags. What do you say?',
          questionFr: 'Quelqu\'un vous aide a porter vos sacs. Que dites-vous ?',
          options: ['Sorry', 'Excuse me', 'Thank you', 'Goodbye'],
          correctIndex: 2,
          explanation: '"Thank you" /θæŋk juː/ expresses gratitude. The "th" sound is made by putting your tongue between your teeth.',
          explanationFr: '"Thank you" /θæŋk juː/ exprime la gratitude. Le son "th" se fait en placant la langue entre les dents.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate this sentence into English.',
          instructionFr: 'Traduisez cette phrase en anglais.',
          sourceFr: 'Excusez-moi, ou est la gare ?',
          targetEn: 'Excuse me, where is the station?',
          hint: 'Excuse me, where is the... ?',
          explanation: '"Excuse me" is used to politely get someone\'s attention before asking a question.',
          explanationFr: '"Excuse me" s\'utilise pour attirer poliment l\'attention de quelqu\'un avant de poser une question.',
        },
        {
          type: 'fill',
          sentence: 'Good ___, did you sleep well?',
          sentenceFr: 'Bon ___, as-tu bien dormi ?',
          answer: 'morning',
          options: ['morning', 'night', 'bye', 'sorry'],
          explanation: '"Good morning" is used from sunrise until about noon. After noon, use "good afternoon".',
          explanationFr: '"Good morning" s\'utilise du lever du soleil jusqu\'a environ midi. Apres midi, on dit "good afternoon".',
        },
        {
          type: 'mcq',
          question: 'When do you say "Good night"?',
          questionFr: 'Quand dit-on "Good night" ?',
          options: [
            'When you arrive at work in the morning',
            'When you say goodbye in the evening or go to bed',
            'When you answer the phone',
            'When you meet someone new',
          ],
          correctIndex: 1,
          explanation: '"Good night" is ONLY used when leaving or going to bed. It is NOT a greeting! To greet someone in the evening, say "good evening".',
          explanationFr: '"Good night" s\'utilise UNIQUEMENT quand on part ou quand on va se coucher. Ce n\'est PAS une salutation ! Pour saluer le soir, on dit "good evening".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Desole, je ne comprends pas.',
          targetEn: 'Sorry, I don\'t understand.',
          hint: 'Sorry, I don\'t...',
          explanation: '"Sorry" can mean "desole" (apology) or be used to politely say you didn\'t understand.',
          explanationFr: '"Sorry" peut signifier "desole" (excuse) ou etre utilise pour dire poliment que vous n\'avez pas compris.',
        },
        {
          type: 'sentence_build',
          instruction: 'Put the words in the correct order to make a sentence.',
          instructionFr: 'Mettez les mots dans le bon ordre pour former une phrase.',
          words: ['Welcome', 'to', 'our', 'home'],
          correctOrder: [0, 1, 2, 3],
          targetSentence: 'Welcome to our home.',
          targetFr: 'Bienvenue chez nous.',
          explanation: 'In English, we say "welcome TO" a place. The preposition "to" indicates the destination.',
          explanationFr: 'En anglais, on dit "welcome TO" un lieu. La preposition "to" indique la destination.',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence from these words.',
          instructionFr: 'Construisez la phrase a partir de ces mots.',
          words: ['Thank', 'you', 'for', 'your', 'help'],
          correctOrder: [0, 1, 2, 3, 4],
          targetSentence: 'Thank you for your help.',
          targetFr: 'Merci pour votre aide.',
          explanation: '"Thank you FOR something" — we use "for" to indicate what we are thankful about.',
          explanationFr: '"Thank you FOR something" — on utilise "for" pour indiquer la raison du remerciement.',
        },
      ],
    },
  },

  // ── Lesson 2: Pronouns & "to be" ─────────────────────────────────────────
  {
    level: 'A1' as const,
    theme: 'foundation-pronouns-be',
    is_premium: false,
    content_json: {
      title: { fr: 'Les pronoms et le verbe "etre"', en: 'Pronouns & the verb "to be"' },
      description: {
        fr: 'Maitrisez les 9 pronoms personnels et conjuguez "to be" (am, is, are).',
        en: 'Master the 9 personal pronouns and conjugate "to be" (am, is, are).',
      },
      emoji: '👤',
      duration: 12,
      xpReward: 30,
      vocabulary: ['I', 'you', 'he', 'she', 'it', 'we', 'they', 'my', 'your'],
      grammar_focus: 'Subject + am/is/are + complement',
      exercises: [
        {
          type: 'mcq',
          question: 'Which form of "to be" goes with "I"?',
          questionFr: 'Quelle forme de "to be" va avec "I" ?',
          options: ['I is', 'I are', 'I am', 'I be'],
          correctIndex: 2,
          explanation: 'The verb "to be" has 3 forms in present tense: I AM, you/we/they ARE, he/she/it IS. "I am" is the only correct combination.',
          explanationFr: 'Le verbe "to be" a 3 formes au present : I AM, you/we/they ARE, he/she/it IS. "I am" est la seule combinaison correcte.',
        },
        {
          type: 'fill',
          sentence: '___ is a teacher.',
          sentenceFr: '___ est professeur.',
          answer: 'He',
          options: ['He', 'I', 'They', 'We'],
          explanation: '"He" /hiː/ refers to a male person. It uses "is" because he/she/it always take "is".',
          explanationFr: '"He" /hiː/ designe une personne masculine. Il utilise "is" car he/she/it prennent toujours "is".',
        },
        {
          type: 'mcq',
          question: 'Complete: "___ are happy." (talking about yourself and a friend)',
          questionFr: 'Completez : "___ are happy." (en parlant de vous et d\'un ami)',
          options: ['I', 'He', 'She', 'We'],
          correctIndex: 3,
          explanation: '"We" /wiː/ means "nous" — it refers to yourself + one or more people. "We" uses "are".',
          explanationFr: '"We" /wiː/ signifie "nous" — il designe vous + une ou plusieurs personnes. "We" utilise "are".',
        },
        {
          type: 'sentence_build',
          instruction: 'Put the words in the correct order.',
          instructionFr: 'Mettez les mots dans le bon ordre.',
          words: ['She', 'is', 'my', 'sister'],
          correctOrder: [0, 1, 2, 3],
          targetSentence: 'She is my sister.',
          targetFr: 'Elle est ma soeur.',
          explanation: 'English sentence structure: SUBJECT + VERB + COMPLEMENT. "She" (subject) + "is" (verb) + "my sister" (complement).',
          explanationFr: 'Structure anglaise : SUJET + VERBE + COMPLEMENT. "She" (sujet) + "is" (verbe) + "my sister" (complement).',
        },
        {
          type: 'fill',
          sentence: 'They ___ at school.',
          sentenceFr: 'Ils ___ a l\'ecole.',
          answer: 'are',
          options: ['am', 'is', 'are', 'be'],
          explanation: '"They" (ils/elles) always uses "are". Remember: I am, you are, he/she/it is, we are, they are.',
          explanationFr: '"They" (ils/elles) utilise toujours "are". Retenez : I am, you are, he/she/it is, we are, they are.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Je suis etudiant.',
          targetEn: 'I am a student.',
          hint: 'I am a...',
          explanation: 'In English, you MUST use "a/an" before a job or role: "I am A student", not "I am student".',
          explanationFr: 'En anglais, on DOIT utiliser "a/an" devant un metier ou un role : "I am A student", pas "I am student".',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence.',
          instructionFr: 'Construisez la phrase.',
          words: ['It', 'is', 'a', 'cat'],
          correctOrder: [0, 1, 2, 3],
          targetSentence: 'It is a cat.',
          targetFr: 'C\'est un chat.',
          explanation: '"It" is used for animals and things. In French you say "c\'est", in English "it is" (subject + verb).',
          explanationFr: '"It" s\'utilise pour les animaux et les choses. En francais on dit "c\'est", en anglais "it is" (sujet + verbe).',
        },
        {
          type: 'mcq',
          question: 'What does "my" mean?',
          questionFr: 'Que signifie "my" ?',
          options: ['ton / votre', 'mon / ma', 'son / sa', 'leur'],
          correctIndex: 1,
          explanation: '"My" /maɪ/ is the possessive form of "I". It means "mon, ma, mes". Example: "my book" = "mon livre".',
          explanationFr: '"My" /maɪ/ est la forme possessive de "I". Il signifie "mon, ma, mes". Exemple : "my book" = "mon livre".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Quel est ton nom ?',
          targetEn: 'What is your name?',
          hint: 'What is your... ?',
          explanation: '"Your" means "ton/ta/votre". Unlike French, there is no tu/vous distinction in modern English.',
          explanationFr: '"Your" signifie "ton/ta/votre". Contrairement au francais, il n\'y a pas de distinction tu/vous en anglais moderne.',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the question.',
          instructionFr: 'Construisez la question.',
          words: ['Are', 'you', 'my', 'friend', '?'],
          correctOrder: [0, 1, 2, 3, 4],
          targetSentence: 'Are you my friend?',
          targetFr: 'Es-tu mon ami ?',
          explanation: 'To make a YES/NO question with "be", INVERT subject and verb: "You are" → "Are you?".',
          explanationFr: 'Pour faire une question OUI/NON avec "be", on INVERSE sujet et verbe : "You are" → "Are you?".',
        },
      ],
    },
  },

  // ── Lesson 3: Yes, No & Basic Words ───────────────────────────────────────
  {
    level: 'A1' as const,
    theme: 'foundation-basics',
    is_premium: false,
    content_json: {
      title: { fr: 'Oui, non et mots de base', en: 'Yes, No & Basic Words' },
      description: {
        fr: 'Les mots fondamentaux : yes, no, okay, et les noms de base (name, man, woman, child, friend).',
        en: 'Fundamental words: yes, no, okay, and basic nouns (name, man, woman, child, friend).',
      },
      emoji: '✅',
      duration: 8,
      xpReward: 20,
      vocabulary: ['yes', 'no', 'okay', 'name', 'man', 'woman', 'child', 'friend'],
      exercises: [
        {
          type: 'mcq',
          question: '"Is this your book?" — "Yes, it is ___ book."',
          questionFr: '"C\'est ton livre ?" — "Oui, c\'est ___ livre."',
          options: ['his', 'her', 'my', 'your'],
          correctIndex: 2,
          explanation: 'When someone asks "Is this YOUR book?" and you answer "yes", you switch to "MY" because now you are talking about yourself.',
          explanationFr: 'Quand on vous demande "Is this YOUR book?" et vous repondez "yes", vous passez a "MY" car vous parlez de vous-meme.',
        },
        {
          type: 'fill',
          sentence: 'The ___ is playing in the park.',
          sentenceFr: 'L\'___ joue dans le parc.',
          answer: 'child',
          options: ['child', 'man', 'name', 'okay'],
          explanation: '"Child" /tʃaɪld/ means "enfant". The plural is irregular: "children" (not "childs").',
          explanationFr: '"Child" /tʃaɪld/ signifie "enfant". Le pluriel est irregulier : "children" (pas "childs").',
        },
        {
          type: 'mcq',
          question: 'What is the plural of "man"?',
          questionFr: 'Quel est le pluriel de "man" ?',
          options: ['mans', 'mens', 'men', 'man\'s'],
          correctIndex: 2,
          explanation: '"Man" → "men" is an irregular plural. Similarly, "woman" → "women". These are among the most common irregular plurals.',
          explanationFr: '"Man" → "men" est un pluriel irregulier. De meme, "woman" → "women". Ce sont parmi les pluriels irreguliers les plus courants.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Mon nom est Alex.',
          targetEn: 'My name is Alex.',
          hint: 'My name is...',
          explanation: 'To introduce yourself: "My name is [name]" or more casually "I\'m [name]".',
          explanationFr: 'Pour se presenter : "My name is [nom]" ou plus familierement "I\'m [nom]".',
        },
        {
          type: 'sentence_build',
          instruction: 'Put the words in the correct order.',
          instructionFr: 'Mettez les mots dans le bon ordre.',
          words: ['The', 'woman', 'is', 'kind'],
          correctOrder: [0, 1, 2, 3],
          targetSentence: 'The woman is kind.',
          targetFr: 'La femme est gentille.',
          explanation: 'Structure: THE + NOUN + IS + ADJECTIVE. "The" is the definite article (le/la/les in French).',
          explanationFr: 'Structure : THE + NOM + IS + ADJECTIF. "The" est l\'article defini (le/la/les en francais).',
        },
        {
          type: 'fill',
          sentence: '"Do you want coffee?" — "No, ___ you."',
          sentenceFr: '"Voulez-vous du cafe ?" — "Non, ___ ."',
          answer: 'thank',
          options: ['thank', 'please', 'sorry', 'okay'],
          explanation: '"No, thank you" is the polite way to decline an offer. Never just say "no" — it sounds rude!',
          explanationFr: '"No, thank you" est la facon polie de refuser une offre. Ne dites jamais juste "no" — c\'est impoli !',
        },
        {
          type: 'mcq',
          question: 'What does "okay" mean?',
          questionFr: 'Que signifie "okay" ?',
          options: ['Non', 'D\'accord', 'Merci', 'Desole'],
          correctIndex: 1,
          explanation: '"Okay" (or "OK") /oʊˈkeɪ/ means "d\'accord" or "ca va". It\'s one of the most universal English words.',
          explanationFr: '"Okay" (ou "OK") /oʊˈkeɪ/ signifie "d\'accord" ou "ca va". C\'est l\'un des mots anglais les plus universels.',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence.',
          instructionFr: 'Construisez la phrase.',
          words: ['She', 'is', 'my', 'friend'],
          correctOrder: [0, 1, 2, 3],
          targetSentence: 'She is my friend.',
          targetFr: 'Elle est mon amie.',
          explanation: '"Friend" /frɛnd/ is gender-neutral in English — no masculine/feminine form like in French (ami/amie).',
          explanationFr: '"Friend" /frɛnd/ est neutre en anglais — pas de forme masculine/feminine comme en francais (ami/amie).',
        },
      ],
    },
  },

  // ── Lesson 4: Question Words ──────────────────────────────────────────────
  {
    level: 'A1' as const,
    theme: 'foundation-questions',
    is_premium: false,
    content_json: {
      title: { fr: 'Les mots interrogatifs', en: 'Question Words' },
      description: {
        fr: 'Apprenez a poser des questions avec what, where, when, who, why, how.',
        en: 'Learn to ask questions with what, where, when, who, why, how.',
      },
      emoji: '❓',
      duration: 12,
      xpReward: 30,
      vocabulary: ['what', 'where', 'when', 'who', 'why', 'how', 'how much', 'how many'],
      grammar_focus: 'Question word + am/is/are + subject?',
      exercises: [
        {
          type: 'mcq',
          question: 'Which question word means "ou" in French?',
          questionFr: 'Quel mot interrogatif signifie "ou" en francais ?',
          options: ['What', 'When', 'Where', 'Who'],
          correctIndex: 2,
          explanation: '"Where" /wɛr/ = "ou". Used for location/place questions. Example: "Where is the bathroom?"',
          explanationFr: '"Where" /wɛr/ = "ou". Utilise pour les questions de lieu. Exemple : "Where is the bathroom?" (Ou sont les toilettes ?)',
        },
        {
          type: 'fill',
          sentence: '___ is your name?',
          sentenceFr: '___ est ton nom ?',
          answer: 'What',
          options: ['What', 'Where', 'Who', 'When'],
          explanation: '"What" /wɒt/ = "quoi/que/quel". Used when asking about things or information.',
          explanationFr: '"What" /wɒt/ = "quoi/que/quel". Utilise pour poser des questions sur des choses ou des informations.',
        },
        {
          type: 'mcq',
          question: '___ are you sad?',
          questionFr: '___ es-tu triste ?',
          options: ['What', 'Where', 'When', 'Why'],
          correctIndex: 3,
          explanation: '"Why" /waɪ/ = "pourquoi". Used to ask for a reason. The answer usually starts with "because".',
          explanationFr: '"Why" /waɪ/ = "pourquoi". Utilise pour demander une raison. La reponse commence generalement par "because" (parce que).',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the question.',
          instructionFr: 'Construisez la question.',
          words: ['Where', 'do', 'you', 'live', '?'],
          correctOrder: [0, 1, 2, 3, 4],
          targetSentence: 'Where do you live?',
          targetFr: 'Ou habites-tu ?',
          explanation: 'Question structure: QUESTION WORD + DO/DOES + SUBJECT + VERB. "Do" is used with I/you/we/they.',
          explanationFr: 'Structure de question : MOT INTERROGATIF + DO/DOES + SUJET + VERBE. "Do" s\'utilise avec I/you/we/they.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Qui est-elle ?',
          targetEn: 'Who is she?',
          hint: 'Who is... ?',
          explanation: '"Who" /huː/ = "qui". For people only. With "is": "Who is she?" (= "Qui est-elle ?").',
          explanationFr: '"Who" /huː/ = "qui". Pour les personnes uniquement. Avec "is" : "Who is she?" (= "Qui est-elle ?").',
        },
        {
          type: 'fill',
          sentence: '___ is the meeting?',
          sentenceFr: '___ est la reunion ?',
          answer: 'When',
          options: ['When', 'What', 'Who', 'Where'],
          explanation: '"When" /wɛn/ = "quand". Used for time-related questions.',
          explanationFr: '"When" /wɛn/ = "quand". Utilise pour les questions liees au temps.',
        },
        {
          type: 'mcq',
          question: 'What is the difference between "how much" and "how many"?',
          questionFr: 'Quelle est la difference entre "how much" et "how many" ?',
          options: [
            '"How much" for uncountable, "how many" for countable',
            '"How much" for people, "how many" for things',
            'They mean the same thing',
            '"How many" is more formal',
          ],
          correctIndex: 0,
          explanation: '"How much" = for uncountable things (water, money, time). "How many" = for countable things (people, books, days).',
          explanationFr: '"How much" = pour les choses non denombrables (eau, argent, temps). "How many" = pour les choses denombrables (personnes, livres, jours).',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the question.',
          instructionFr: 'Construisez la question.',
          words: ['How', 'are', 'you', '?'],
          correctOrder: [0, 1, 2, 3],
          targetSentence: 'How are you?',
          targetFr: 'Comment vas-tu ?',
          explanation: '"How are you?" is THE most important question in English. Common answers: "I\'m fine", "I\'m good", "Not bad".',
          explanationFr: '"How are you?" est LA question la plus importante en anglais. Reponses courantes : "I\'m fine", "I\'m good", "Not bad".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Combien ca coute ?',
          targetEn: 'How much is this?',
          hint: 'How much... ?',
          explanation: '"How much is this?" is essential for shopping. You can also say "How much does this cost?".',
          explanationFr: '"How much is this?" est essentiel pour faire du shopping. On peut aussi dire "How much does this cost?".',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the question.',
          instructionFr: 'Construisez la question.',
          words: ['What', 'is', 'this', '?'],
          correctOrder: [0, 1, 2, 3],
          targetSentence: 'What is this?',
          targetFr: 'Qu\'est-ce que c\'est ?',
          explanation: '"What is this?" is the simplest way to ask about something you don\'t know. Point at the object and ask!',
          explanationFr: '"What is this?" est la facon la plus simple de demander ce que quelque chose est. Montrez l\'objet et demandez !',
        },
      ],
    },
  },

  // ── Lesson 5: Essential Verbs (Part 1) ────────────────────────────────────
  {
    level: 'A1' as const,
    theme: 'foundation-verbs-1',
    is_premium: false,
    content_json: {
      title: { fr: 'Les verbes essentiels (partie 1)', en: 'Essential Verbs (Part 1)' },
      description: {
        fr: 'Apprenez les 10 verbes les plus importants : be, have, do, go, come, want, need, like, know, think.',
        en: 'Learn the 10 most important verbs: be, have, do, go, come, want, need, like, know, think.',
      },
      emoji: '🏃',
      duration: 15,
      xpReward: 35,
      vocabulary: ['be', 'have', 'do', 'go', 'come', 'want', 'need', 'like', 'know', 'think'],
      grammar_focus: 'Subject + verb (+ object)',
      exercises: [
        {
          type: 'mcq',
          question: 'Complete: "I ___ a cat."',
          questionFr: 'Completez : "J\' ___ un chat."',
          options: ['has', 'have', 'am', 'do'],
          correctIndex: 1,
          explanation: '"Have" /hæv/ = "avoir". I/you/we/they HAVE, but he/she/it HAS. "I have a cat" = "J\'ai un chat".',
          explanationFr: '"Have" /hæv/ = "avoir". I/you/we/they HAVE, mais he/she/it HAS. "I have a cat" = "J\'ai un chat".',
        },
        {
          type: 'fill',
          sentence: 'I ___ to school every day.',
          sentenceFr: 'Je ___ a l\'ecole tous les jours.',
          answer: 'go',
          options: ['go', 'come', 'do', 'be'],
          explanation: '"Go" /ɡoʊ/ = "aller". "Go TO" a place: "I go TO school". We always use "to" after "go".',
          explanationFr: '"Go" /ɡoʊ/ = "aller". "Go TO" un lieu : "I go TO school". On utilise toujours "to" apres "go".',
        },
        {
          type: 'mcq',
          question: 'What does "I want water" mean?',
          questionFr: 'Que signifie "I want water" ?',
          options: ['J\'ai de l\'eau', 'Je veux de l\'eau', 'J\'aime l\'eau', 'J\'ai besoin d\'eau'],
          correctIndex: 1,
          explanation: '"Want" /wɒnt/ = "vouloir". "Need" = "avoir besoin". "Want" is a desire, "need" is a necessity.',
          explanationFr: '"Want" /wɒnt/ = "vouloir". "Need" = "avoir besoin". "Want" est un desir, "need" est une necessite.',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence.',
          instructionFr: 'Construisez la phrase.',
          words: ['I', 'like', 'music'],
          correctOrder: [0, 1, 2],
          targetSentence: 'I like music.',
          targetFr: 'J\'aime la musique.',
          explanation: '"Like" = "aimer" (in general). In English, NO article before general concepts: "I like music" (NOT "I like the music").',
          explanationFr: '"Like" = "aimer" (en general). En anglais, PAS d\'article devant les concepts generaux : "I like music" (PAS "I like the music").',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'J\'ai besoin d\'aide.',
          targetEn: 'I need help.',
          hint: 'I need...',
          explanation: '"Need" /niːd/ = "avoir besoin de". No "of" needed in English: "I need help" (NOT "I need of help").',
          explanationFr: '"Need" /niːd/ = "avoir besoin de". Pas de "of" en anglais : "I need help" (PAS "I need of help").',
        },
        {
          type: 'fill',
          sentence: 'I ___ the answer.',
          sentenceFr: 'Je ___ la reponse.',
          answer: 'know',
          options: ['know', 'think', 'want', 'need'],
          explanation: '"Know" /noʊ/ = "savoir/connaitre". The K is silent! You pronounce it just like "no".',
          explanationFr: '"Know" /noʊ/ = "savoir/connaitre". Le K est muet ! On le prononce exactement comme "no".',
        },
        {
          type: 'mcq',
          question: '"Come here, please." — What does this mean?',
          questionFr: '"Come here, please." — Que signifie cette phrase ?',
          options: ['Va la-bas, s\'il te plait', 'Viens ici, s\'il te plait', 'Reste ici, s\'il te plait', 'Pars d\'ici, s\'il te plait'],
          correctIndex: 1,
          explanation: '"Come" /kʌm/ = "venir" (towards the speaker). "Go" = "aller" (away from the speaker). This is the same distinction as in French (venir/aller).',
          explanationFr: '"Come" /kʌm/ = "venir" (vers celui qui parle). "Go" = "aller" (loin de celui qui parle). C\'est la meme distinction qu\'en francais.',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the question.',
          instructionFr: 'Construisez la question.',
          words: ['What', 'do', 'you', 'do', '?'],
          correctOrder: [0, 1, 2, 3, 4],
          targetSentence: 'What do you do?',
          targetFr: 'Que fais-tu (dans la vie) ?',
          explanation: '"What do you do?" asks about someone\'s job. The first "do" is the helper verb, the second "do" means "faire".',
          explanationFr: '"What do you do?" demande le metier de quelqu\'un. Le premier "do" est l\'auxiliaire, le second "do" signifie "faire".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Je pense que c\'est bien.',
          targetEn: 'I think it\'s good.',
          hint: 'I think it\'s...',
          explanation: '"Think" /θɪŋk/ = "penser". "I think (that)..." — the word "that" is often omitted in casual English.',
          explanationFr: '"Think" /θɪŋk/ = "penser". "I think (that)..." — le mot "that" est souvent omis en anglais courant.',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence.',
          instructionFr: 'Construisez la phrase.',
          words: ['Do', 'you', 'want', 'coffee', '?'],
          correctOrder: [0, 1, 2, 3, 4],
          targetSentence: 'Do you want coffee?',
          targetFr: 'Veux-tu du cafe ?',
          explanation: 'To make a question with regular verbs, add "DO" at the start: "You want" → "DO you want?".',
          explanationFr: 'Pour faire une question avec les verbes reguliers, ajoutez "DO" au debut : "You want" → "DO you want?".',
        },
      ],
    },
  },

  // ── Lesson 6: Essential Verbs (Part 2) ────────────────────────────────────
  {
    level: 'A1' as const,
    theme: 'foundation-verbs-2',
    is_premium: false,
    content_json: {
      title: { fr: 'Les verbes essentiels (partie 2)', en: 'Essential Verbs (Part 2)' },
      description: {
        fr: 'Continuez avec 10 verbes du quotidien : see, eat, drink, speak, understand, work, live, can, make, take, give.',
        en: 'Continue with 10 everyday verbs: see, eat, drink, speak, understand, work, live, can, make, take, give.',
      },
      emoji: '🗣️',
      duration: 15,
      xpReward: 35,
      vocabulary: ['see', 'eat', 'drink', 'speak', 'understand', 'work', 'live', 'can', 'make', 'take', 'give'],
      exercises: [
        {
          type: 'mcq',
          question: 'Complete: "Do you ___ English?"',
          questionFr: 'Completez : "Parlez-vous ___ ?"',
          options: ['speak', 'talk', 'say', 'tell'],
          correctIndex: 0,
          explanation: '"Speak" a language. "Do you speak English?" is the #1 question for travelers. "Speak" = parler (a language).',
          explanationFr: '"Speak" une langue. "Do you speak English?" est la question n°1 pour les voyageurs. "Speak" = parler (une langue).',
        },
        {
          type: 'fill',
          sentence: 'I ___ coffee every morning.',
          sentenceFr: 'Je ___ du cafe chaque matin.',
          answer: 'drink',
          options: ['drink', 'eat', 'make', 'take'],
          explanation: '"Drink" /drɪŋk/ = "boire" (for liquids). "Eat" /iːt/ = "manger" (for food). Don\'t mix them up!',
          explanationFr: '"Drink" /drɪŋk/ = "boire" (pour les liquides). "Eat" /iːt/ = "manger" (pour la nourriture). Ne les confondez pas !',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence.',
          instructionFr: 'Construisez la phrase.',
          words: ['I', 'can', 'swim'],
          correctOrder: [0, 1, 2],
          targetSentence: 'I can swim.',
          targetFr: 'Je sais nager.',
          explanation: '"Can" /kæn/ = "pouvoir/savoir (faire)". It\'s a MODAL verb: no "to", no "s" with he/she. "I can", "she can" (NOT "she cans").',
          explanationFr: '"Can" /kæn/ = "pouvoir/savoir (faire)". C\'est un verbe MODAL : pas de "to", pas de "s" avec he/she. "I can", "she can" (PAS "she cans").',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Je comprends le francais.',
          targetEn: 'I understand French.',
          hint: 'I understand...',
          explanation: '"Understand" /ˌʌndərˈstænd/ = "comprendre". No article before language names: "I understand French" (NOT "the French").',
          explanationFr: '"Understand" /ˌʌndərˈstænd/ = "comprendre". Pas d\'article devant les noms de langues : "I understand French" (PAS "the French").',
        },
        {
          type: 'mcq',
          question: '"I live in Paris." — What does "live" mean here?',
          questionFr: '"I live in Paris." — Que signifie "live" ici ?',
          options: ['travailler', 'habiter', 'voyager', 'aimer'],
          correctIndex: 1,
          explanation: '"Live" /lɪv/ = "habiter/vivre". "I live IN" a city/country. Use "in" for locations.',
          explanationFr: '"Live" /lɪv/ = "habiter/vivre". "I live IN" une ville/un pays. On utilise "in" pour les lieux.',
        },
        {
          type: 'fill',
          sentence: 'I ___ breakfast at 8 o\'clock.',
          sentenceFr: 'Je ___ le petit-dejeuner a 8 heures.',
          answer: 'eat',
          options: ['eat', 'drink', 'take', 'make'],
          explanation: '"Eat" /iːt/ = "manger". In English, we also say "have breakfast" (= prendre le petit-dejeuner).',
          explanationFr: '"Eat" /iːt/ = "manger". En anglais, on dit aussi "have breakfast" (= prendre le petit-dejeuner).',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence.',
          instructionFr: 'Construisez la phrase.',
          words: ['I', 'work', 'in', 'a', 'hospital'],
          correctOrder: [0, 1, 2, 3, 4],
          targetSentence: 'I work in a hospital.',
          targetFr: 'Je travaille dans un hopital.',
          explanation: '"Work IN" a place. Use "a" (not "the") when talking about the type of place in general.',
          explanationFr: '"Work IN" un lieu. Utilisez "a" (pas "the") quand on parle du type de lieu en general.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Donne-moi le stylo, s\'il te plait.',
          targetEn: 'Give me the pen, please.',
          hint: 'Give me the...',
          explanation: '"Give" /ɡɪv/ = "donner". Structure: "Give + ME/HIM/HER + object". The indirect object comes first!',
          explanationFr: '"Give" /ɡɪv/ = "donner". Structure : "Give + ME/HIM/HER + objet". Le complement indirect vient en premier !',
        },
        {
          type: 'mcq',
          question: 'What is the difference between "make" and "do"?',
          questionFr: 'Quelle est la difference entre "make" et "do" ?',
          options: [
            '"Make" = create something, "do" = perform an action',
            'They mean the same thing',
            '"Make" is formal, "do" is informal',
            '"Make" is for questions, "do" is for answers',
          ],
          correctIndex: 0,
          explanation: '"Make" = create/produce (make coffee, make a cake). "Do" = perform/carry out (do homework, do exercise).',
          explanationFr: '"Make" = creer/produire (make coffee, make a cake). "Do" = executer/realiser (do homework, do exercise).',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence.',
          instructionFr: 'Construisez la phrase.',
          words: ['Take', 'this', 'book'],
          correctOrder: [0, 1, 2],
          targetSentence: 'Take this book.',
          targetFr: 'Prends ce livre.',
          explanation: '"Take" /teɪk/ = "prendre". It\'s an imperative here (command): no subject needed. Just start with the verb!',
          explanationFr: '"Take" /teɪk/ = "prendre". C\'est un imperatif ici (ordre) : pas de sujet necessaire. Commencez directement par le verbe !',
        },
      ],
    },
  },

  // ── Lesson 7: Time & Frequency ────────────────────────────────────────────
  {
    level: 'A1' as const,
    theme: 'foundation-time',
    is_premium: false,
    content_json: {
      title: { fr: 'Le temps et la frequence', en: 'Time & Frequency' },
      description: {
        fr: 'Les mots du temps (today, tomorrow, yesterday) et la frequence (always, never, sometimes).',
        en: 'Time words (today, tomorrow, yesterday) and frequency (always, never, sometimes).',
      },
      emoji: '⏰',
      duration: 10,
      xpReward: 25,
      vocabulary: ['today', 'tomorrow', 'yesterday', 'now', 'always', 'never', 'sometimes', 'morning', 'night', 'day'],
      grammar_focus: 'Frequency adverbs go BEFORE the main verb but AFTER "be"',
      exercises: [
        {
          type: 'mcq',
          question: 'Where does "always" go in the sentence "I ___ wake up early"?',
          questionFr: 'Ou se place "always" dans la phrase "I ___ wake up early" ?',
          options: ['After the verb', 'Before the verb', 'At the end', 'At the start'],
          correctIndex: 1,
          explanation: 'Frequency adverbs (always, never, sometimes, often, usually) go BEFORE the main verb: "I ALWAYS wake up early".',
          explanationFr: 'Les adverbes de frequence (always, never, sometimes, often, usually) se placent AVANT le verbe principal : "I ALWAYS wake up early".',
        },
        {
          type: 'fill',
          sentence: '___ is Monday.',
          sentenceFr: '___ c\'est lundi.',
          answer: 'Today',
          options: ['Today', 'Tomorrow', 'Yesterday', 'Now'],
          explanation: '"Today" /təˈdeɪ/ = "aujourd\'hui". "Tomorrow" = "demain". "Yesterday" = "hier".',
          explanationFr: '"Today" /təˈdeɪ/ = "aujourd\'hui". "Tomorrow" = "demain". "Yesterday" = "hier".',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence.',
          instructionFr: 'Construisez la phrase.',
          words: ['I', 'never', 'eat', 'meat'],
          correctOrder: [0, 1, 2, 3],
          targetSentence: 'I never eat meat.',
          targetFr: 'Je ne mange jamais de viande.',
          explanation: '"Never" goes BEFORE the verb. In English, "never" already includes the negation — don\'t add "don\'t": "I never eat" (NOT "I don\'t never eat").',
          explanationFr: '"Never" se place AVANT le verbe. En anglais, "never" contient deja la negation — n\'ajoutez pas "don\'t" : "I never eat" (PAS "I don\'t never eat").',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'A demain.',
          targetEn: 'See you tomorrow.',
          hint: 'See you...',
          explanation: '"See you tomorrow" is the natural English way to say "a demain". We don\'t say "until tomorrow".',
          explanationFr: '"See you tomorrow" est la facon naturelle de dire "a demain" en anglais. On ne dit pas "until tomorrow".',
        },
        {
          type: 'mcq',
          question: '"I am eating now." — What does "now" emphasize?',
          questionFr: '"I am eating now." — Qu\'est-ce que "now" souligne ?',
          options: ['A past action', 'An action happening right at this moment', 'A future action', 'A habitual action'],
          correctIndex: 1,
          explanation: '"Now" /naʊ/ = "maintenant". It emphasizes that the action is happening at this very moment (present continuous).',
          explanationFr: '"Now" /naʊ/ = "maintenant". Il souligne que l\'action se passe en ce moment meme (present continu).',
        },
        {
          type: 'fill',
          sentence: 'I ___ go to the park on Sundays.',
          sentenceFr: 'Je vais ___ au parc le dimanche.',
          answer: 'sometimes',
          options: ['sometimes', 'never', 'yesterday', 'tomorrow'],
          explanation: '"Sometimes" /ˈsʌmtaɪmz/ = "parfois". It can go before the verb OR at the start/end of the sentence.',
          explanationFr: '"Sometimes" /ˈsʌmtaɪmz/ = "parfois". Il peut se placer avant le verbe OU au debut/a la fin de la phrase.',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence.',
          instructionFr: 'Construisez la phrase.',
          words: ['I', 'run', 'in', 'the', 'morning'],
          correctOrder: [0, 1, 2, 3, 4],
          targetSentence: 'I run in the morning.',
          targetFr: 'Je cours le matin.',
          explanation: '"In the morning" = "le matin". Time expressions with parts of the day use "in": in the morning, in the afternoon, in the evening. Exception: "at night".',
          explanationFr: '"In the morning" = "le matin". Les expressions de temps avec les parties de la journee utilisent "in" : in the morning, in the afternoon, in the evening. Exception : "at night".',
        },
        {
          type: 'mcq',
          question: 'Which preposition do we use with "night"?',
          questionFr: 'Quelle preposition utilise-t-on avec "night" ?',
          options: ['in the night', 'on the night', 'at night', 'to the night'],
          correctIndex: 2,
          explanation: 'We say "AT night" (not "in the night"). This is an exception! "In the morning/afternoon/evening" BUT "at night".',
          explanationFr: 'On dit "AT night" (pas "in the night"). C\'est une exception ! "In the morning/afternoon/evening" MAIS "at night".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Hier il faisait beau.',
          targetEn: 'Yesterday was sunny.',
          hint: 'Yesterday was...',
          explanation: '"Yesterday" uses past tense. "Was" is the past of "is". "It was sunny" = "il faisait beau".',
          explanationFr: '"Yesterday" utilise le passe. "Was" est le passe de "is". "It was sunny" = "il faisait beau".',
        },
        {
          type: 'fill',
          sentence: 'It is a beautiful ___.',
          sentenceFr: 'C\'est une belle ___.',
          answer: 'day',
          options: ['day', 'morning', 'night', 'today'],
          explanation: '"Day" /deɪ/ = "jour/journee". "Today" = "aujourd\'hui" (adverb). "Day" is a noun you can describe: "a beautiful day".',
          explanationFr: '"Day" /deɪ/ = "jour/journee". "Today" = "aujourd\'hui" (adverbe). "Day" est un nom qu\'on peut decrire : "a beautiful day".',
        },
      ],
    },
  },

  // ── Lesson 8: Adjectives & Intensifiers ───────────────────────────────────
  {
    level: 'A1' as const,
    theme: 'foundation-adjectives',
    is_premium: false,
    content_json: {
      title: { fr: 'Les adjectifs et intensifieurs', en: 'Adjectives & Intensifiers' },
      description: {
        fr: 'Decrivez le monde : good/bad, big/small, new/old, happy/tired, hot/cold + very, not, too.',
        en: 'Describe the world: good/bad, big/small, new/old, happy/tired, hot/cold + very, not, too.',
      },
      emoji: '🎨',
      duration: 12,
      xpReward: 30,
      vocabulary: ['good', 'bad', 'big', 'small', 'new', 'old', 'happy', 'tired', 'hot', 'cold', 'very', 'not', 'too'],
      grammar_focus: 'Subject + be + (very/too/not) + adjective',
      exercises: [
        {
          type: 'mcq',
          question: 'In English, where does the adjective go?',
          questionFr: 'En anglais, ou se place l\'adjectif ?',
          options: [
            'After the noun: "a car big"',
            'Before the noun: "a big car"',
            'It depends on the sentence',
            'Adjectives don\'t exist in English',
          ],
          correctIndex: 1,
          explanation: 'In English, adjectives go BEFORE the noun: "a big car", "a small cat". This is the opposite of French ("une grande voiture").',
          explanationFr: 'En anglais, les adjectifs se placent AVANT le nom : "a big car", "a small cat". C\'est l\'inverse du francais ("une grande voiture").',
        },
        {
          type: 'fill',
          sentence: 'The coffee is too ___. I can\'t drink it.',
          sentenceFr: 'Le cafe est trop ___. Je ne peux pas le boire.',
          answer: 'hot',
          options: ['hot', 'cold', 'good', 'big'],
          explanation: '"Hot" /hɒt/ = "chaud". "Too hot" = "trop chaud" — "too" indicates excess (negative meaning).',
          explanationFr: '"Hot" /hɒt/ = "chaud". "Too hot" = "trop chaud" — "too" indique l\'exces (sens negatif).',
        },
        {
          type: 'mcq',
          question: 'What is the difference between "very" and "too"?',
          questionFr: 'Quelle est la difference entre "very" et "too" ?',
          options: [
            'They mean the same thing',
            '"Very" is positive/neutral, "too" means excess (problem)',
            '"Too" is positive, "very" is negative',
            '"Very" is informal, "too" is formal',
          ],
          correctIndex: 1,
          explanation: '"Very good" = great! (positive). "Too hot" = so hot it\'s a problem (negative). "Very" intensifies, "too" = excess.',
          explanationFr: '"Very good" = genial ! (positif). "Too hot" = si chaud que c\'est un probleme (negatif). "Very" intensifie, "too" = exces.',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence.',
          instructionFr: 'Construisez la phrase.',
          words: ['I', 'am', 'very', 'happy'],
          correctOrder: [0, 1, 2, 3],
          targetSentence: 'I am very happy.',
          targetFr: 'Je suis tres heureux.',
          explanation: 'Structure: SUBJECT + AM/IS/ARE + VERY + ADJECTIVE. "Very" comes between the verb and the adjective.',
          explanationFr: 'Structure : SUJET + AM/IS/ARE + VERY + ADJECTIF. "Very" se place entre le verbe et l\'adjectif.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Je ne suis pas fatigue.',
          targetEn: 'I am not tired.',
          hint: 'I am not...',
          explanation: 'To make "be" negative, add "not" AFTER: "I am NOT tired". Contraction: "I\'m not tired".',
          explanationFr: 'Pour rendre "be" negatif, ajoutez "not" APRES : "I am NOT tired". Contraction : "I\'m not tired".',
        },
        {
          type: 'fill',
          sentence: 'I have a ___ phone. I bought it yesterday.',
          sentenceFr: 'J\'ai un ___ telephone. Je l\'ai achete hier.',
          answer: 'new',
          options: ['new', 'old', 'big', 'bad'],
          explanation: '"New" /njuː/ = "nouveau/neuf". "Old" = "vieux/ancien". They are opposites.',
          explanationFr: '"New" /njuː/ = "nouveau/neuf". "Old" = "vieux/ancien". Ce sont des opposes.',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence.',
          instructionFr: 'Construisez la phrase.',
          words: ['The', 'cat', 'is', 'small'],
          correctOrder: [0, 1, 2, 3],
          targetSentence: 'The cat is small.',
          targetFr: 'Le chat est petit.',
          explanation: 'When the adjective comes AFTER "be" (is/am/are), no article change needed: "The cat IS small" (describing the cat).',
          explanationFr: 'Quand l\'adjectif vient APRES "be" (is/am/are), pas de changement d\'article : "The cat IS small" (on decrit le chat).',
        },
        {
          type: 'mcq',
          question: '"This is a bad idea." — What does "bad" mean?',
          questionFr: '"This is a bad idea." — Que signifie "bad" ?',
          options: ['bonne', 'mauvaise', 'grande', 'nouvelle'],
          correctIndex: 1,
          explanation: '"Bad" /bæd/ = "mauvais". Opposite of "good". "A bad idea" = "une mauvaise idee".',
          explanationFr: '"Bad" /bæd/ = "mauvais". Oppose de "good". "A bad idea" = "une mauvaise idee".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'L\'eau est froide.',
          targetEn: 'The water is cold.',
          hint: 'The water is...',
          explanation: '"Cold" /koʊld/ = "froid". Opposite of "hot". Use with "be": "The water IS cold".',
          explanationFr: '"Cold" /koʊld/ = "froid". Oppose de "hot". Utilisez avec "be" : "The water IS cold".',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence.',
          instructionFr: 'Construisez la phrase.',
          words: ['The', 'building', 'is', 'very', 'old'],
          correctOrder: [0, 1, 2, 3, 4],
          targetSentence: 'The building is very old.',
          targetFr: 'Le batiment est tres ancien.',
          explanation: 'You can combine "very" with any adjective to strengthen it: very old, very big, very good, very cold.',
          explanationFr: 'On peut combiner "very" avec n\'importe quel adjectif pour le renforcer : very old, very big, very good, very cold.',
        },
      ],
    },
  },

  // ── Lesson 9: Connectors & Quantifiers ────────────────────────────────────
  {
    level: 'A1' as const,
    theme: 'foundation-connectors',
    is_premium: false,
    content_json: {
      title: { fr: 'Les connecteurs et quantifieurs', en: 'Connectors & Quantifiers' },
      description: {
        fr: 'Liez vos idees avec and, but, or, because, so et quantifiez avec some, all, many, a lot.',
        en: 'Link your ideas with and, but, or, because, so and quantify with some, all, many, a lot.',
      },
      emoji: '🔗',
      duration: 12,
      xpReward: 30,
      vocabulary: ['and', 'but', 'or', 'because', 'so', 'with', 'without', 'a lot', 'some', 'all', 'many'],
      exercises: [
        {
          type: 'mcq',
          question: 'Complete: "I am tired ___ happy."',
          questionFr: 'Completez : "Je suis fatigue ___ heureux."',
          options: ['and', 'but', 'or', 'because'],
          correctIndex: 1,
          explanation: '"But" /bʌt/ = "mais". Used for contrast. Being tired AND happy is a contrast, so we use "but".',
          explanationFr: '"But" /bʌt/ = "mais". Utilise pour le contraste. Etre fatigue ET heureux est un contraste, donc on utilise "but".',
        },
        {
          type: 'fill',
          sentence: 'I like tea ___ coffee.',
          sentenceFr: 'J\'aime le the ___ le cafe.',
          answer: 'and',
          options: ['and', 'but', 'or', 'so'],
          explanation: '"And" /ænd/ = "et". Used to add things together. "Tea AND coffee" = both.',
          explanationFr: '"And" /ænd/ = "et". Utilise pour ajouter des elements. "Tea AND coffee" = les deux.',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence.',
          instructionFr: 'Construisez la phrase.',
          words: ['I', 'am', 'happy', 'because', 'it', 'is', 'sunny'],
          correctOrder: [0, 1, 2, 3, 4, 5, 6],
          targetSentence: 'I am happy because it is sunny.',
          targetFr: 'Je suis heureux parce qu\'il fait beau.',
          explanation: '"Because" /bɪˈkɒz/ = "parce que". It introduces the REASON. Cause and effect: effect + because + cause.',
          explanationFr: '"Because" /bɪˈkɒz/ = "parce que". Il introduit la RAISON. Cause et effet : effet + because + cause.',
        },
        {
          type: 'mcq',
          question: '"Tea or coffee?" — What does this mean?',
          questionFr: '"Tea or coffee?" — Que signifie cette phrase ?',
          options: [
            'You must have both',
            'Choose one: tea or coffee',
            'Neither tea nor coffee',
            'Tea is better than coffee',
          ],
          correctIndex: 1,
          explanation: '"Or" /ɔːr/ = "ou". Used to present a choice between options. "Tea OR coffee?" = choose one.',
          explanationFr: '"Or" /ɔːr/ = "ou". Utilise pour presenter un choix entre des options. "Tea OR coffee?" = choisissez-en un.',
        },
        {
          type: 'fill',
          sentence: 'I am tired, ___ I sleep.',
          sentenceFr: 'Je suis fatigue, ___ je dors.',
          answer: 'so',
          options: ['so', 'but', 'or', 'and'],
          explanation: '"So" /soʊ/ = "donc/alors". Used for consequence. "I\'m tired, SO I sleep" = cause → consequence.',
          explanationFr: '"So" /soʊ/ = "donc/alors". Utilise pour la consequence. "I\'m tired, SO I sleep" = cause → consequence.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Cafe sans sucre.',
          targetEn: 'Coffee without sugar.',
          hint: 'Coffee without...',
          explanation: '"Without" /wɪðˈaʊt/ = "sans". "With" = "avec". "Without" is "with" + "out" (the opposite of with).',
          explanationFr: '"Without" /wɪðˈaʊt/ = "sans". "With" = "avec". "Without" est "with" + "out" (l\'oppose de with).',
        },
        {
          type: 'mcq',
          question: '"I want some water." — What does "some" mean?',
          questionFr: '"I want some water." — Que signifie "some" ?',
          options: ['beaucoup de', 'pas de', 'un peu de / du', 'tout'],
          correctIndex: 2,
          explanation: '"Some" /sʌm/ = "du/de la/quelques". Used in positive sentences for an unspecified quantity.',
          explanationFr: '"Some" /sʌm/ = "du/de la/quelques". Utilise dans les phrases positives pour une quantite non specifiee.',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence.',
          instructionFr: 'Construisez la phrase.',
          words: ['I', 'go', 'with', 'my', 'friend'],
          correctOrder: [0, 1, 2, 3, 4],
          targetSentence: 'I go with my friend.',
          targetFr: 'Je vais avec mon ami.',
          explanation: '"With" /wɪð/ = "avec". Used to indicate accompaniment. "I go WITH my friend" = together.',
          explanationFr: '"With" /wɪð/ = "avec". Utilise pour indiquer l\'accompagnement. "I go WITH my friend" = ensemble.',
        },
        {
          type: 'fill',
          sentence: '___ the students are here.',
          sentenceFr: '___ les etudiants sont ici.',
          answer: 'All',
          options: ['All', 'Some', 'Many', 'A lot'],
          explanation: '"All" /ɔːl/ = "tous/toutes". "All the students" = 100% of them.',
          explanationFr: '"All" /ɔːl/ = "tous/toutes". "All the students" = 100% d\'entre eux.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Il y a beaucoup de gens.',
          targetEn: 'There are many people.',
          hint: 'There are many...',
          explanation: '"Many" = "beaucoup de" (countable). "There are" introduces existence. "People" is already plural (not "peoples").',
          explanationFr: '"Many" = "beaucoup de" (denombrable). "There are" introduit l\'existence. "People" est deja pluriel (pas "peoples").',
        },
      ],
    },
  },

  // ── Lesson 10: Prepositions & Building Your First Sentences ───────────────
  {
    level: 'A1' as const,
    theme: 'foundation-sentences',
    is_premium: false,
    content_json: {
      title: { fr: 'Prepositions et construction de phrases', en: 'Prepositions & Building Sentences' },
      description: {
        fr: 'Maitrisez in, on, at, to, from, here, there et apprenez a construire vos premieres phrases completes.',
        en: 'Master in, on, at, to, from, here, there and learn to build your first complete sentences.',
      },
      emoji: '🏗️',
      duration: 15,
      xpReward: 40,
      vocabulary: ['here', 'there', 'in', 'on', 'at', 'to', 'from'],
      grammar_focus: 'Subject + verb + preposition + place/time',
      exercises: [
        {
          type: 'mcq',
          question: 'Which preposition do we use with cities? "I live ___ Paris."',
          questionFr: 'Quelle preposition utilise-t-on avec les villes ? "I live ___ Paris."',
          options: ['at', 'on', 'in', 'to'],
          correctIndex: 2,
          explanation: 'Use "IN" for cities, countries, and continents: "in Paris", "in France", "in Europe". Think of being INSIDE a place.',
          explanationFr: 'Utilisez "IN" pour les villes, pays et continents : "in Paris", "in France", "in Europe". Pensez a etre A L\'INTERIEUR d\'un lieu.',
        },
        {
          type: 'fill',
          sentence: 'The book is ___ the table.',
          sentenceFr: 'Le livre est ___ la table.',
          answer: 'on',
          options: ['on', 'in', 'at', 'to'],
          explanation: '"On" = "sur". Used for surfaces: on the table, on the wall, on the floor. The object touches the surface.',
          explanationFr: '"On" = "sur". Utilise pour les surfaces : on the table, on the wall, on the floor. L\'objet touche la surface.',
        },
        {
          type: 'mcq',
          question: '"I am ___ home." — Which preposition?',
          questionFr: '"I am ___ home." — Quelle preposition ?',
          options: ['in', 'on', 'at', 'to'],
          correctIndex: 2,
          explanation: '"At" is used for specific locations/points: at home, at school, at work, at the station. Think of a precise point.',
          explanationFr: '"At" s\'utilise pour des lieux/points specifiques : at home, at school, at work, at the station. Pensez a un point precis.',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the sentence.',
          instructionFr: 'Construisez la phrase.',
          words: ['I', 'am', 'from', 'France'],
          correctOrder: [0, 1, 2, 3],
          targetSentence: 'I am from France.',
          targetFr: 'Je viens de France.',
          explanation: '"From" /frɒm/ = "de/depuis". Used for origin: "I am FROM France" = "Je viens DE France". No article before country names (usually).',
          explanationFr: '"From" /frɒm/ = "de/depuis". Utilise pour l\'origine : "I am FROM France" = "Je viens DE France". Pas d\'article devant les noms de pays (generalement).',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Viens ici.',
          targetEn: 'Come here.',
          hint: 'Come...',
          explanation: '"Here" /hɪr/ = "ici" (near the speaker). "There" /ðɛr/ = "la-bas" (far from the speaker).',
          explanationFr: '"Here" /hɪr/ = "ici" (pres de celui qui parle). "There" /ðɛr/ = "la-bas" (loin de celui qui parle).',
        },
        {
          type: 'fill',
          sentence: 'I go ___ school every day.',
          sentenceFr: 'Je vais ___ l\'ecole tous les jours.',
          answer: 'to',
          options: ['to', 'at', 'in', 'on'],
          explanation: '"To" /tuː/ = "a/vers". Used for DIRECTION/movement: "go TO school", "go TO work". You are moving toward a destination.',
          explanationFr: '"To" /tuː/ = "a/vers". Utilise pour la DIRECTION/le mouvement : "go TO school", "go TO work". Vous vous deplacez vers une destination.',
        },
        {
          type: 'mcq',
          question: 'What is the difference between "at school" and "to school"?',
          questionFr: 'Quelle est la difference entre "at school" et "to school" ?',
          options: [
            '"At school" = you are there. "To school" = you are going there.',
            'They mean the same thing',
            '"At" is formal, "to" is informal',
            '"At" is American, "to" is British',
          ],
          correctIndex: 0,
          explanation: '"I am AT school" = I\'m already there (location). "I go TO school" = I\'m moving there (direction). AT = position, TO = movement.',
          explanationFr: '"I am AT school" = j\'y suis deja (lieu). "I go TO school" = je m\'y rends (direction). AT = position, TO = mouvement.',
        },
        {
          type: 'sentence_build',
          instruction: 'Build a complete sentence about yourself.',
          instructionFr: 'Construisez une phrase complete sur vous-meme.',
          words: ['I', 'live', 'in', 'a', 'big', 'house'],
          correctOrder: [0, 1, 2, 3, 4, 5],
          targetSentence: 'I live in a big house.',
          targetFr: 'J\'habite dans une grande maison.',
          explanation: 'Full sentence structure: SUBJECT (I) + VERB (live) + PREPOSITION (in) + ARTICLE (a) + ADJECTIVE (big) + NOUN (house).',
          explanationFr: 'Structure complete : SUJET (I) + VERBE (live) + PREPOSITION (in) + ARTICLE (a) + ADJECTIF (big) + NOM (house).',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'L\'ecole est la-bas.',
          targetEn: 'The school is there.',
          hint: 'The school is...',
          explanation: '"There" points to a location away from you. "The school is THERE" = you can see it or point at it.',
          explanationFr: '"There" indique un lieu eloigne de vous. "The school is THERE" = vous pouvez le voir ou le montrer du doigt.',
        },
        {
          type: 'sentence_build',
          instruction: 'Build the most complex sentence you can!',
          instructionFr: 'Construisez la phrase la plus complete possible !',
          words: ['I', 'am', 'happy', 'because', 'I', 'live', 'in', 'a', 'beautiful', 'city'],
          correctOrder: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
          targetSentence: 'I am happy because I live in a beautiful city.',
          targetFr: 'Je suis heureux parce que j\'habite dans une belle ville.',
          explanation: 'You just built a complex sentence! Two clauses linked by "because": [I am happy] + because + [I live in a beautiful city]. You\'re ready for more!',
          explanationFr: 'Vous venez de construire une phrase complexe ! Deux propositions liees par "because" : [I am happy] + because + [I live in a beautiful city]. Vous etes pret pour la suite !',
        },
      ],
    },
  },
];

async function main() {
  console.log('=== Seeding Foundation A1 Lessons ===\n');

  // Get current max order for A1
  const maxOrder = await prisma.lesson.aggregate({
    where: { level: 'A1' },
    _max: { order: true },
  });
  let nextOrder = (maxOrder._max.order ?? 0) + 1;

  let created = 0;
  let skipped = 0;

  for (const lesson of foundationLessons) {
    // Check if already exists
    const existing = await prisma.lesson.findFirst({
      where: { level: lesson.level, theme: lesson.theme },
    });

    if (existing) {
      console.log(`  [skip] ${lesson.theme} (already exists)`);
      skipped++;
      continue;
    }

    await prisma.lesson.create({
      data: {
        level: lesson.level,
        theme: lesson.theme,
        order: nextOrder,
        is_premium: lesson.is_premium,
        content_json: lesson.content_json as any,
      },
    });

    console.log(`  [created] ${lesson.theme} (order: ${nextOrder})`);
    nextOrder++;
    created++;
  }

  console.log(`\nDone! Created: ${created}, Skipped: ${skipped}`);

  // Print summary
  const stats = await prisma.lesson.groupBy({
    by: ['level'],
    _count: true,
  });
  console.log('\nTotal lessons by level:');
  for (const s of stats.sort((a, b) => a.level.localeCompare(b.level))) {
    console.log(`  ${s.level}: ${s._count} lessons`);
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
