import { PrismaClient } from '@prisma/client';

const lessons = [
  // ══════════════════════════════════════════════════════════════════
  // A1 — Beginner (15 lessons, order 1–15)
  // ══════════════════════════════════════════════════════════════════
  {
    level: 'A1' as const,
    theme: 'greetings',
    order: 1,
    is_premium: false,
    content_json: {
      title: { fr: 'Salutations & Presentations', en: 'Greetings & Introductions' },
      description: {
        fr: 'Apprenez a vous saluer et a vous presenter en anglais.',
        en: 'Learn how to greet people and introduce yourself in English.',
      },
      emoji: '\uD83D\uDC4B',
      duration: 8,
      xpReward: 20,
      exercises: [
        {
          type: 'mcq',
          question: 'How do you say "Bonjour" in English?',
          questionFr: 'Comment dit-on "Bonjour" en anglais ?',
          options: ['Goodbye', 'Hello', 'Sorry', 'Please'],
          correctIndex: 1,
          explanation: '"Hello" is the most common English greeting.',
          explanationFr: '"Hello" est la salutation la plus courante en anglais.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate this sentence into English.',
          instructionFr: 'Traduisez cette phrase en anglais.',
          sourceFr: "Je m'appelle Marie.",
          targetEn: 'My name is Marie.',
          hint: 'My name is...',
        },
        {
          type: 'mcq',
          question: 'What does "How are you?" mean?',
          questionFr: 'Que signifie "How are you?" ?',
          options: ['Where are you?', 'What is your name?', 'How are you?', 'How old are you?'],
          correctIndex: 2,
          explanation: '"How are you?" means "Comment vas-tu ?".',
          explanationFr: '"How are you?" se traduit par "Comment allez-vous ?".',
        },
        {
          type: 'fill',
          sentence: 'Nice to ___ you!',
          sentenceFr: 'Ravi de vous ___ !',
          answer: 'meet',
          options: ['meet', 'see', 'know', 'find'],
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Enchante de vous rencontrer.',
          targetEn: 'Nice to meet you.',
        },
      ],
    },
  },
  {
    level: 'A1' as const,
    theme: 'numbers',
    order: 2,
    is_premium: false,
    content_json: {
      title: { fr: 'Les chiffres de 1 a 20', en: 'Numbers 1\u201320' },
      description: {
        fr: 'Apprenez les chiffres de 1 a 20 en anglais.',
        en: 'Learn numbers from 1 to 20 in English.',
      },
      emoji: '\uD83D\uDD22',
      duration: 7,
      xpReward: 20,
      exercises: [
        {
          type: 'mcq',
          question: 'Which word represents the number 5?',
          questionFr: 'Quel mot represente le chiffre 5 ?',
          options: ['Four', 'Three', 'Five', 'Six'],
          correctIndex: 2,
          explanation: '5 = "five" in English.',
          explanationFr: '5 se dit "five" en anglais.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: "J'ai quinze ans.",
          targetEn: 'I am fifteen years old.',
          hint: 'I am ... years old.',
        },
        {
          type: 'fill',
          sentence: 'There are ___ days in a week.',
          sentenceFr: 'Il y a ___ jours dans une semaine.',
          answer: 'seven',
          options: ['five', 'six', 'seven', 'eight'],
        },
        {
          type: 'mcq',
          question: 'Which number comes after "twelve"?',
          questionFr: 'Quel nombre vient apres "twelve" (douze) ?',
          options: ['Eleven', 'Fourteen', 'Thirteen', 'Twenty'],
          correctIndex: 2,
          explanation: 'After twelve (12) comes thirteen (13).',
          explanationFr: 'Apres douze (12) vient treize (13) = "thirteen".',
        },
      ],
    },
  },
  {
    level: 'A1' as const,
    theme: 'colors',
    order: 3,
    is_premium: false,
    content_json: {
      title: { fr: 'Couleurs & Adjectifs', en: 'Colors & Adjectives' },
      description: {
        fr: 'Les couleurs et adjectifs de base en anglais.',
        en: 'Basic colors and adjectives in English.',
      },
      emoji: '\uD83C\uDFA8',
      duration: 7,
      xpReward: 20,
      exercises: [
        {
          type: 'mcq',
          question: 'What color is the sky?',
          questionFr: 'De quelle couleur est le ciel ?',
          options: ['Red', 'Green', 'Blue', 'Yellow'],
          correctIndex: 2,
          explanation: 'The sky is blue.',
          explanationFr: 'Le ciel est bleu = "blue".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'La voiture est rouge.',
          targetEn: 'The car is red.',
        },
        {
          type: 'fill',
          sentence: 'Snow is ___.',
          sentenceFr: 'La neige est ___ (blanche).',
          answer: 'white',
          options: ['black', 'white', 'grey', 'brown'],
        },
        {
          type: 'mcq',
          question: 'How do you say "grand / gros" in English?',
          questionFr: 'Comment dit-on "grand / gros" en anglais ?',
          options: ['Small', 'Big', 'Long', 'Heavy'],
          correctIndex: 1,
          explanation: '"Big" means grand or gros.',
          explanationFr: '"Big" signifie grand ou gros.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Le chat est petit et noir.',
          targetEn: 'The cat is small and black.',
          hint: 'The cat is ... and ...',
        },
      ],
    },
  },
  {
    level: 'A1' as const,
    theme: 'family',
    order: 4,
    is_premium: false,
    content_json: {
      title: { fr: 'Les membres de la famille', en: 'Family Members' },
      description: {
        fr: 'Vocabulaire pour parler de sa famille.',
        en: 'Vocabulary for family members.',
      },
      emoji: '\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC67\u200D\uD83D\uDC66',
      duration: 8,
      xpReward: 20,
      exercises: [
        {
          type: 'mcq',
          question: 'What is the English word for "mere"?',
          questionFr: 'Quel est le mot anglais pour "mere" ?',
          options: ['Sister', 'Mother', 'Daughter', 'Aunt'],
          correctIndex: 1,
          explanation: '"Mere" = "mother" in English.',
          explanationFr: '"Mere" se traduit par "mother".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: "Mon pere s'appelle Paul.",
          targetEn: "My father's name is Paul.",
          hint: "My father's name is...",
        },
        {
          type: 'fill',
          sentence: 'My parents are my ___ and my father.',
          sentenceFr: 'Mes parents sont ma ___ (mere) et mon pere.',
          answer: 'mother',
          options: ['sister', 'mother', 'aunt', 'grandmother'],
        },
        {
          type: 'mcq',
          question: 'What is the English word for "frere"?',
          questionFr: 'Quel est le mot anglais pour "frere" ?',
          options: ['Friend', 'Father', 'Brother', 'Boy'],
          correctIndex: 2,
          explanation: '"Frere" = "brother" in English.',
          explanationFr: '"Frere" se traduit par "brother".',
        },
      ],
    },
  },
  {
    level: 'A1' as const,
    theme: 'food',
    order: 5,
    is_premium: false,
    content_json: {
      title: { fr: 'Nourriture & Boissons', en: 'Food & Drinks' },
      description: {
        fr: 'Vocabulaire pour la nourriture et les boissons.',
        en: 'Vocabulary for food and drinks.',
      },
      emoji: '\uD83C\uDF54',
      duration: 8,
      xpReward: 20,
      exercises: [
        {
          type: 'mcq',
          question: 'What is the English word for "eau"?',
          questionFr: 'Quel est le mot anglais pour "eau" ?',
          options: ['Milk', 'Juice', 'Water', 'Coffee'],
          correctIndex: 2,
          explanation: '"Eau" = "water" in English.',
          explanationFr: '"Eau" se traduit par "water".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: "Je voudrais une pomme, s'il vous plait.",
          targetEn: 'I would like an apple, please.',
          hint: 'I would like...',
        },
        {
          type: 'fill',
          sentence: 'I drink ___ every morning.',
          sentenceFr: 'Je bois du ___ (cafe) chaque matin.',
          answer: 'coffee',
          options: ['food', 'bread', 'coffee', 'rice'],
        },
        {
          type: 'mcq',
          question: 'Which of these is a drink?',
          questionFr: 'Lequel de ces mots est une boisson ?',
          options: ['Bread', 'Orange juice', 'Rice', 'Cheese'],
          correctIndex: 1,
          explanation: '"Orange juice" is a drink.',
          explanationFr: '"Orange juice" signifie "jus d\'orange", c\'est une boisson.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Le pain est delicieux.',
          targetEn: 'The bread is delicious.',
        },
      ],
    },
  },
  {
    level: 'A1' as const,
    theme: 'days_months',
    order: 6,
    is_premium: false,
    content_json: {
      title: { fr: 'Jours & Mois', en: 'Days & Months' },
      description: {
        fr: "Les jours de la semaine et les mois de l'annee.",
        en: 'Days of the week and months of the year.',
      },
      emoji: '\uD83D\uDCC5',
      duration: 7,
      xpReward: 20,
      exercises: [
        {
          type: 'mcq',
          question: 'What day comes after "Monday"?',
          questionFr: 'Quel jour vient apres "Monday" (lundi) ?',
          options: ['Sunday', 'Tuesday', 'Saturday', 'Wednesday'],
          correctIndex: 1,
          explanation: 'Monday \u2192 Tuesday.',
          explanationFr: 'Apres lundi (Monday) vient mardi = "Tuesday".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: "Aujourd'hui c'est lundi.",
          targetEn: 'Today is Monday.',
        },
        {
          type: 'fill',
          sentence: 'There are ___ months in a year.',
          sentenceFr: 'Il y a ___ mois dans une annee.',
          answer: 'twelve',
          options: ['ten', 'eleven', 'twelve', 'thirteen'],
        },
        {
          type: 'mcq',
          question: 'What is the English word for "decembre"?',
          questionFr: 'Quel est le mot anglais pour "decembre" ?',
          options: ['November', 'January', 'October', 'December'],
          correctIndex: 3,
          explanation: '"Decembre" = "December" in English.',
          explanationFr: '"Decembre" se traduit par "December".',
        },
      ],
    },
  },
  {
    level: 'A1' as const,
    theme: 'body_parts',
    order: 7,
    is_premium: false,
    content_json: {
      title: { fr: 'Les parties du corps', en: 'Body Parts' },
      description: {
        fr: 'Apprenez le vocabulaire des parties du corps.',
        en: 'Learn vocabulary for body parts.',
      },
      emoji: '\uD83E\uDDB6',
      duration: 7,
      xpReward: 20,
      exercises: [
        {
          type: 'mcq',
          question: 'What is the English word for "tete"?',
          questionFr: 'Quel est le mot anglais pour "tete" ?',
          options: ['Hand', 'Head', 'Heart', 'Hair'],
          correctIndex: 1,
          explanation: '"Tete" = "head" in English.',
          explanationFr: '"Tete" se traduit par "head".',
        },
        {
          type: 'fill',
          sentence: 'I see with my ___.',
          sentenceFr: 'Je vois avec mes ___ (yeux).',
          answer: 'eyes',
          options: ['ears', 'eyes', 'hands', 'nose'],
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: "J'ai mal a la tete.",
          targetEn: 'I have a headache.',
          hint: 'I have a...',
        },
        {
          type: 'mcq',
          question: 'Which body part do you use to hear?',
          questionFr: 'Quelle partie du corps utilise-t-on pour entendre ?',
          options: ['Eyes', 'Mouth', 'Ears', 'Nose'],
          correctIndex: 2,
          explanation: 'We hear with our ears.',
          explanationFr: 'On entend avec les oreilles = "ears".',
        },
      ],
    },
  },
  {
    level: 'A1' as const,
    theme: 'clothes',
    order: 8,
    is_premium: false,
    content_json: {
      title: { fr: 'Les vetements', en: 'Clothes' },
      description: {
        fr: 'Vocabulaire des vetements du quotidien.',
        en: 'Everyday clothing vocabulary.',
      },
      emoji: '\uD83D\uDC55',
      duration: 7,
      xpReward: 20,
      exercises: [
        {
          type: 'mcq',
          question: 'What do you wear on your feet?',
          questionFr: 'Que porte-t-on aux pieds ?',
          options: ['Hat', 'Gloves', 'Shoes', 'Scarf'],
          correctIndex: 2,
          explanation: 'We wear shoes on our feet.',
          explanationFr: 'On porte des chaussures ("shoes") aux pieds.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Elle porte une robe bleue.',
          targetEn: 'She is wearing a blue dress.',
          hint: 'She is wearing...',
        },
        {
          type: 'fill',
          sentence: 'He put on his ___ because it was cold.',
          sentenceFr: 'Il a mis son ___ (manteau) parce qu\'il faisait froid.',
          answer: 'coat',
          options: ['shorts', 'coat', 'sandals', 'hat'],
        },
        {
          type: 'mcq',
          question: 'What is a "T-shirt"?',
          questionFr: 'Qu\'est-ce qu\'un "T-shirt" ?',
          options: ['Un pantalon', 'Un chapeau', 'Un maillot a manches courtes', 'Une jupe'],
          correctIndex: 2,
          explanation: 'A T-shirt is a short-sleeved casual top.',
          explanationFr: 'Un T-shirt est un haut decontracte a manches courtes.',
        },
      ],
    },
  },
  {
    level: 'A1' as const,
    theme: 'animals',
    order: 9,
    is_premium: false,
    content_json: {
      title: { fr: 'Les animaux', en: 'Animals' },
      description: {
        fr: 'Les animaux les plus courants en anglais.',
        en: 'The most common animals in English.',
      },
      emoji: '\uD83D\uDC36',
      duration: 7,
      xpReward: 20,
      exercises: [
        {
          type: 'mcq',
          question: 'What animal says "meow"?',
          questionFr: 'Quel animal fait "meow" ?',
          options: ['Dog', 'Bird', 'Cat', 'Fish'],
          correctIndex: 2,
          explanation: 'A cat says "meow".',
          explanationFr: 'Le chat ("cat") fait "meow".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: "J'ai un chien et deux chats.",
          targetEn: 'I have a dog and two cats.',
          hint: 'I have a dog and...',
        },
        {
          type: 'fill',
          sentence: 'The ___ lives in the ocean.',
          sentenceFr: 'Le ___ (poisson) vit dans l\'ocean.',
          answer: 'fish',
          options: ['bird', 'dog', 'fish', 'horse'],
        },
        {
          type: 'mcq',
          question: 'What is the English word for "oiseau"?',
          questionFr: 'Quel est le mot anglais pour "oiseau" ?',
          options: ['Bear', 'Bird', 'Bee', 'Bat'],
          correctIndex: 1,
          explanation: '"Oiseau" = "bird" in English.',
          explanationFr: '"Oiseau" se traduit par "bird".',
        },
      ],
    },
  },
  {
    level: 'A1' as const,
    theme: 'at_home',
    order: 10,
    is_premium: false,
    content_json: {
      title: { fr: 'A la maison', en: 'At Home' },
      description: {
        fr: 'Les pieces et objets de la maison.',
        en: 'Rooms and objects in the house.',
      },
      emoji: '\uD83C\uDFE0',
      duration: 8,
      xpReward: 20,
      exercises: [
        {
          type: 'mcq',
          question: 'Where do you cook food?',
          questionFr: 'Ou cuisine-t-on ?',
          options: ['Bedroom', 'Bathroom', 'Kitchen', 'Garden'],
          correctIndex: 2,
          explanation: 'We cook in the kitchen.',
          explanationFr: 'On cuisine dans la cuisine = "kitchen".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'La chambre est grande.',
          targetEn: 'The bedroom is big.',
          hint: 'The bedroom is...',
        },
        {
          type: 'fill',
          sentence: 'I watch TV in the ___.',
          sentenceFr: 'Je regarde la television dans le ___ (salon).',
          answer: 'living room',
          options: ['kitchen', 'bathroom', 'living room', 'garage'],
        },
        {
          type: 'mcq',
          question: 'What is the English word for "fenetre"?',
          questionFr: 'Quel est le mot anglais pour "fenetre" ?',
          options: ['Door', 'Window', 'Wall', 'Floor'],
          correctIndex: 1,
          explanation: '"Fenetre" = "window".',
          explanationFr: '"Fenetre" se traduit par "window".',
        },
      ],
    },
  },
  {
    level: 'A1' as const,
    theme: 'weather',
    order: 11,
    is_premium: true,
    content_json: {
      title: { fr: 'La meteo', en: 'The Weather' },
      description: {
        fr: 'Parler du temps qu\'il fait.',
        en: 'Talk about the weather.',
      },
      emoji: '\u2600\uFE0F',
      duration: 7,
      xpReward: 25,
      exercises: [
        {
          type: 'mcq',
          question: 'What does "It\'s raining" mean?',
          questionFr: 'Que signifie "It\'s raining" ?',
          options: ['Il neige', 'Il pleut', 'Il fait chaud', 'Il fait froid'],
          correctIndex: 1,
          explanation: '"It\'s raining" means il pleut.',
          explanationFr: '"It\'s raining" signifie "il pleut".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Il fait beau aujourd\'hui.',
          targetEn: 'The weather is nice today.',
          hint: 'The weather is...',
        },
        {
          type: 'fill',
          sentence: 'It is very ___ in summer.',
          sentenceFr: 'Il fait tres ___ (chaud) en ete.',
          answer: 'hot',
          options: ['cold', 'hot', 'rainy', 'snowy'],
        },
        {
          type: 'mcq',
          question: 'What season comes after winter?',
          questionFr: 'Quelle saison vient apres l\'hiver ?',
          options: ['Summer', 'Autumn', 'Spring', 'Winter'],
          correctIndex: 2,
          explanation: 'Spring comes after winter.',
          explanationFr: 'Le printemps ("spring") vient apres l\'hiver.',
        },
      ],
    },
  },
  {
    level: 'A1' as const,
    theme: 'professions',
    order: 12,
    is_premium: true,
    content_json: {
      title: { fr: 'Les metiers', en: 'Professions' },
      description: {
        fr: 'Vocabulaire des metiers courants.',
        en: 'Common profession vocabulary.',
      },
      emoji: '\uD83D\uDC68\u200D\u2695\uFE0F',
      duration: 7,
      xpReward: 25,
      exercises: [
        {
          type: 'mcq',
          question: 'Who works in a hospital?',
          questionFr: 'Qui travaille dans un hopital ?',
          options: ['Teacher', 'Doctor', 'Chef', 'Pilot'],
          correctIndex: 1,
          explanation: 'A doctor works in a hospital.',
          explanationFr: 'Un docteur ("doctor") travaille a l\'hopital.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Mon pere est professeur.',
          targetEn: 'My father is a teacher.',
          hint: 'My father is a...',
        },
        {
          type: 'fill',
          sentence: 'A ___ flies airplanes.',
          sentenceFr: 'Un ___ (pilote) pilote des avions.',
          answer: 'pilot',
          options: ['driver', 'pilot', 'captain', 'engineer'],
        },
        {
          type: 'mcq',
          question: 'What does a "chef" do?',
          questionFr: 'Que fait un "chef" (cuisinier) ?',
          options: ['Teaches students', 'Cooks food', 'Drives a bus', 'Builds houses'],
          correctIndex: 1,
          explanation: 'A chef cooks food in a restaurant.',
          explanationFr: 'Un chef cuisinier prepare des plats au restaurant.',
        },
      ],
    },
  },
  {
    level: 'A1' as const,
    theme: 'school_supplies',
    order: 13,
    is_premium: true,
    content_json: {
      title: { fr: 'Les fournitures scolaires', en: 'School Supplies' },
      description: {
        fr: 'Les objets de l\'ecole en anglais.',
        en: 'School objects in English.',
      },
      emoji: '\u270F\uFE0F',
      duration: 7,
      xpReward: 25,
      exercises: [
        {
          type: 'mcq',
          question: 'What do you write with?',
          questionFr: 'Avec quoi ecrit-on ?',
          options: ['Ruler', 'Pen', 'Eraser', 'Book'],
          correctIndex: 1,
          explanation: 'We write with a pen.',
          explanationFr: 'On ecrit avec un stylo = "pen".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Le livre est sur la table.',
          targetEn: 'The book is on the table.',
          hint: 'The book is...',
        },
        {
          type: 'fill',
          sentence: 'I put my books in my ___.',
          sentenceFr: 'Je mets mes livres dans mon ___ (sac).',
          answer: 'bag',
          options: ['desk', 'bag', 'chair', 'box'],
        },
        {
          type: 'mcq',
          question: 'What is a "notebook"?',
          questionFr: 'Qu\'est-ce qu\'un "notebook" ?',
          options: ['Un ordinateur', 'Un cahier', 'Un crayon', 'Une gomme'],
          correctIndex: 1,
          explanation: 'A notebook is a small book for writing notes.',
          explanationFr: 'Un "notebook" est un cahier pour prendre des notes.',
        },
      ],
    },
  },
  {
    level: 'A1' as const,
    theme: 'sports_hobbies',
    order: 14,
    is_premium: true,
    content_json: {
      title: { fr: 'Sports & Loisirs', en: 'Sports & Hobbies' },
      description: {
        fr: 'Parler de ses activites preferees.',
        en: 'Talk about your favorite activities.',
      },
      emoji: '\u26BD',
      duration: 8,
      xpReward: 25,
      exercises: [
        {
          type: 'mcq',
          question: 'Which sport uses a ball and a net?',
          questionFr: 'Quel sport utilise un ballon et un filet ?',
          options: ['Swimming', 'Tennis', 'Running', 'Cycling'],
          correctIndex: 1,
          explanation: 'Tennis uses a ball and a net.',
          explanationFr: 'Le tennis utilise une balle et un filet.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'J\'aime jouer au football.',
          targetEn: 'I like playing football.',
          hint: 'I like playing...',
        },
        {
          type: 'fill',
          sentence: 'She ___ every morning in the park.',
          sentenceFr: 'Elle ___ (court) chaque matin dans le parc.',
          answer: 'runs',
          options: ['swims', 'runs', 'plays', 'dances'],
        },
        {
          type: 'mcq',
          question: 'What does "I like reading" mean?',
          questionFr: 'Que signifie "I like reading" ?',
          options: ['J\'aime courir', 'J\'aime lire', 'J\'aime cuisiner', 'J\'aime voyager'],
          correctIndex: 1,
          explanation: '"Reading" means lire.',
          explanationFr: '"Reading" signifie "lire".',
        },
      ],
    },
  },
  {
    level: 'A1' as const,
    theme: 'emotions',
    order: 15,
    is_premium: true,
    content_json: {
      title: { fr: 'Les emotions', en: 'Emotions & Feelings' },
      description: {
        fr: 'Exprimer ses emotions en anglais.',
        en: 'Express your emotions in English.',
      },
      emoji: '\uD83D\uDE0A',
      duration: 7,
      xpReward: 25,
      exercises: [
        {
          type: 'mcq',
          question: 'What does "happy" mean?',
          questionFr: 'Que signifie "happy" ?',
          options: ['Triste', 'Heureux', 'Fatigue', 'En colere'],
          correctIndex: 1,
          explanation: '"Happy" means heureux.',
          explanationFr: '"Happy" signifie "heureux / content".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Je suis fatigue.',
          targetEn: 'I am tired.',
          hint: 'I am...',
        },
        {
          type: 'fill',
          sentence: 'She is ___ because she lost her keys.',
          sentenceFr: 'Elle est ___ (triste) parce qu\'elle a perdu ses cles.',
          answer: 'sad',
          options: ['happy', 'sad', 'excited', 'bored'],
        },
        {
          type: 'mcq',
          question: 'Which word means "en colere"?',
          questionFr: 'Quel mot signifie "en colere" ?',
          options: ['Scared', 'Bored', 'Angry', 'Surprised'],
          correctIndex: 2,
          explanation: '"Angry" means en colere.',
          explanationFr: '"Angry" signifie "en colere".',
        },
      ],
    },
  },

  // ══════════════════════════════════════════════════════════════════
  // A2 — Elementary (15 lessons, order 16–30)
  // ══════════════════════════════════════════════════════════════════
  {
    level: 'A2' as const,
    theme: 'daily_routines',
    order: 16,
    is_premium: false,
    content_json: {
      title: { fr: 'La routine quotidienne', en: 'Daily Routines' },
      description: {
        fr: 'Parlez de votre journee typique en anglais.',
        en: 'Talk about your typical day in English.',
      },
      emoji: '\u23F0',
      duration: 8,
      xpReward: 25,
      exercises: [
        {
          type: 'mcq',
          question: 'Which sentence means "Je me reveille a 7h"?',
          questionFr: 'Quelle phrase signifie "Je me reveille a 7h" ?',
          options: [
            "I sleep at 7 o'clock.",
            "I wake up at 7 o'clock.",
            "I eat at 7 o'clock.",
            "I work at 7 o'clock.",
          ],
          correctIndex: 1,
          explanation: '"Wake up" means se reveiller.',
          explanationFr: '"Wake up" = se reveiller.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Je prends mon petit-dejeuner a huit heures.',
          targetEn: "I have breakfast at eight o'clock.",
          hint: 'I have breakfast at...',
        },
        {
          type: 'fill',
          sentence: 'She ___ to work by bus every day.',
          sentenceFr: 'Elle ___ (va) au travail en bus chaque jour.',
          answer: 'goes',
          options: ['go', 'goes', 'going', 'gone'],
        },
        {
          type: 'mcq',
          question: 'What does "go to bed" mean?',
          questionFr: 'Que signifie "go to bed" ?',
          options: ['Se lever', 'Aller au travail', 'Aller se coucher', 'Dejeuner'],
          correctIndex: 2,
          explanation: '"Go to bed" means aller se coucher.',
          explanationFr: '"Go to bed" signifie aller se coucher.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Il se couche a vingt-deux heures.',
          targetEn: "He goes to bed at ten o'clock.",
          hint: 'He goes to bed at...',
        },
      ],
    },
  },
  {
    level: 'A2' as const,
    theme: 'shopping',
    order: 17,
    is_premium: false,
    content_json: {
      title: { fr: 'Les courses / Shopping', en: 'Shopping' },
      description: {
        fr: 'Faire des courses et demander les prix.',
        en: 'Go shopping and ask about prices.',
      },
      emoji: '\uD83D\uDED2',
      duration: 8,
      xpReward: 25,
      exercises: [
        {
          type: 'mcq',
          question: 'How do you ask for the price of something?',
          questionFr: 'Comment demander le prix de quelque chose ?',
          options: ['Where is it?', 'How much is it?', 'What is it?', 'Can I have it?'],
          correctIndex: 1,
          explanation: '"How much is it?" = Combien ca coute ?',
          explanationFr: '"How much is it?" signifie "Combien ca coute ?".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: "C'est trop cher.",
          targetEn: "It's too expensive.",
          hint: "It's too...",
        },
        {
          type: 'fill',
          sentence: 'Do you have this in a ___ size?',
          sentenceFr: 'Avez-vous ceci dans une taille ___ (plus grande) ?',
          answer: 'bigger',
          options: ['small', 'bigger', 'expensive', 'nice'],
        },
        {
          type: 'mcq',
          question: "What does \"I'd like to pay by card\" mean?",
          questionFr: 'Que signifie "I\'d like to pay by card" ?',
          options: [
            'Je voudrais payer en especes.',
            'Je voudrais payer par carte.',
            'Je cherche la caisse.',
            'Avez-vous un recu ?',
          ],
          correctIndex: 1,
          explanation: '"Pay by card" = payer par carte.',
          explanationFr: '"Pay by card" signifie "payer par carte bancaire".',
        },
      ],
    },
  },
  {
    level: 'A2' as const,
    theme: 'telling_time',
    order: 18,
    is_premium: false,
    content_json: {
      title: { fr: "Dire l'heure", en: 'Telling the Time' },
      description: {
        fr: "Dire et demander l'heure en anglais.",
        en: 'Say and ask the time in English.',
      },
      emoji: '\uD83D\uDD50',
      duration: 7,
      xpReward: 25,
      exercises: [
        {
          type: 'mcq',
          question: "What does \"It's half past two\" mean?",
          questionFr: 'Que signifie "It\'s half past two" ?',
          options: [
            'Il est deux heures.',
            'Il est deux heures et demie.',
            'Il est deux heures et quart.',
            'Il est deux heures moins le quart.',
          ],
          correctIndex: 1,
          explanation: '"Half past two" = 2:30.',
          explanationFr: '"Half past two" signifie "deux heures et demie" (2h30).',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Il est trois heures et quart.',
          targetEn: "It's quarter past three.",
          hint: "It's quarter past...",
        },
        {
          type: 'fill',
          sentence: "The train leaves ___ ten o'clock.",
          sentenceFr: 'Le train part ___ dix heures (a).',
          answer: 'at',
          options: ['in', 'on', 'at', 'by'],
        },
        {
          type: 'mcq',
          question: 'What does "What time is it?" mean?',
          questionFr: 'Que signifie "What time is it?" ?',
          options: [
            "C'est l'heure ?",
            'Quelle heure est-il ?',
            'A quelle heure ?',
            'Depuis quand ?',
          ],
          correctIndex: 1,
          explanation: '"What time is it?" = Quelle heure est-il ?',
          explanationFr: '"What time is it?" se traduit par "Quelle heure est-il ?".',
        },
      ],
    },
  },
  {
    level: 'A2' as const,
    theme: 'clothes_shopping',
    order: 19,
    is_premium: false,
    content_json: {
      title: { fr: 'Acheter des vetements', en: 'Clothes Shopping' },
      description: {
        fr: 'Acheter et essayer des vetements en magasin.',
        en: 'Buy and try on clothes in a store.',
      },
      emoji: '\uD83D\uDC57',
      duration: 8,
      xpReward: 25,
      exercises: [
        {
          type: 'mcq',
          question: 'What does "Can I try this on?" mean?',
          questionFr: 'Que signifie "Can I try this on?" ?',
          options: ['Puis-je l\'acheter ?', 'Puis-je l\'essayer ?', 'C\'est a moi ?', 'Combien ca coute ?'],
          correctIndex: 1,
          explanation: '"Try on" means essayer un vetement.',
          explanationFr: '"Try on" signifie essayer un vetement.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Cette jupe est trop petite.',
          targetEn: 'This skirt is too small.',
          hint: 'This skirt is...',
        },
        {
          type: 'fill',
          sentence: 'Where is the ___ room?',
          sentenceFr: 'Ou est la cabine d\'___ (essayage) ?',
          answer: 'fitting',
          options: ['waiting', 'fitting', 'living', 'dining'],
        },
        {
          type: 'mcq',
          question: 'What does "It fits perfectly" mean?',
          questionFr: 'Que signifie "It fits perfectly" ?',
          options: ['C\'est trop grand.', 'C\'est parfait.', 'Ca me va parfaitement.', 'C\'est cher.'],
          correctIndex: 2,
          explanation: '"It fits perfectly" = ca me va parfaitement.',
          explanationFr: '"It fits perfectly" signifie "ca me va parfaitement".',
        },
      ],
    },
  },
  {
    level: 'A2' as const,
    theme: 'weather_forecast',
    order: 20,
    is_premium: false,
    content_json: {
      title: { fr: 'La meteo avancee', en: 'Weather & Forecasts' },
      description: {
        fr: 'Comprendre les previsions meteo en anglais.',
        en: 'Understand weather forecasts in English.',
      },
      emoji: '\uD83C\uDF26\uFE0F',
      duration: 8,
      xpReward: 25,
      exercises: [
        {
          type: 'mcq',
          question: 'What does "cloudy" mean?',
          questionFr: 'Que signifie "cloudy" ?',
          options: ['Ensoleille', 'Nuageux', 'Venteux', 'Pluvieux'],
          correctIndex: 1,
          explanation: '"Cloudy" means nuageux.',
          explanationFr: '"Cloudy" signifie "nuageux".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Il va pleuvoir demain.',
          targetEn: 'It is going to rain tomorrow.',
          hint: 'It is going to...',
        },
        {
          type: 'fill',
          sentence: 'The ___ is blowing strongly today.',
          sentenceFr: 'Le ___ (vent) souffle fort aujourd\'hui.',
          answer: 'wind',
          options: ['rain', 'sun', 'wind', 'snow'],
        },
        {
          type: 'mcq',
          question: 'What does "the temperature is 30 degrees" mean?',
          questionFr: 'Que signifie "the temperature is 30 degrees" ?',
          options: ['Il fait -30.', 'La temperature est de 30 degres.', 'Il neige.', 'Il fait nuit.'],
          correctIndex: 1,
          explanation: '"30 degrees" = 30 degres.',
          explanationFr: '"The temperature is 30 degrees" = la temperature est de 30 degres.',
        },
      ],
    },
  },
  {
    level: 'A2' as const,
    theme: 'past_simple_regular',
    order: 21,
    is_premium: false,
    content_json: {
      title: { fr: 'Le passe simple (regulier)', en: 'Past Simple (Regular Verbs)' },
      description: {
        fr: 'Conjuguer les verbes reguliers au passe.',
        en: 'Use regular verbs in the past tense.',
      },
      emoji: '\u23EA',
      duration: 9,
      xpReward: 30,
      exercises: [
        {
          type: 'mcq',
          question: 'What is the past tense of "walk"?',
          questionFr: 'Quel est le passe du verbe "walk" (marcher) ?',
          options: ['Walks', 'Walking', 'Walked', 'Walken'],
          correctIndex: 2,
          explanation: 'Regular verbs add -ed: walk \u2192 walked.',
          explanationFr: 'Les verbes reguliers ajoutent -ed : walk \u2192 walked.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'J\'ai joue au tennis hier.',
          targetEn: 'I played tennis yesterday.',
          hint: 'I played...',
        },
        {
          type: 'fill',
          sentence: 'She ___ the door and left.',
          sentenceFr: 'Elle a ___ (ferme) la porte et est partie.',
          answer: 'closed',
          options: ['close', 'closed', 'closing', 'closes'],
        },
        {
          type: 'mcq',
          question: 'Which sentence is correct?',
          questionFr: 'Quelle phrase est correcte ?',
          options: ['I watchd TV.', 'I watched TV.', 'I watch TV yesterday.', 'I watching TV.'],
          correctIndex: 1,
          explanation: '"Watch" + -ed = "watched".',
          explanationFr: 'Le passe de "watch" est "watched".',
        },
      ],
    },
  },
  {
    level: 'A2' as const,
    theme: 'past_simple_irregular',
    order: 22,
    is_premium: false,
    content_json: {
      title: { fr: 'Le passe simple (irregulier)', en: 'Past Simple (Irregular Verbs)' },
      description: {
        fr: 'Les verbes irreguliers les plus courants au passe.',
        en: 'The most common irregular verbs in the past tense.',
      },
      emoji: '\uD83D\uDD00',
      duration: 9,
      xpReward: 30,
      exercises: [
        {
          type: 'mcq',
          question: 'What is the past tense of "go"?',
          questionFr: 'Quel est le passe du verbe "go" (aller) ?',
          options: ['Goed', 'Goes', 'Went', 'Going'],
          correctIndex: 2,
          explanation: '"Go" is irregular \u2014 past tense is "went".',
          explanationFr: '"Go" est irregulier \u2014 son passe est "went".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: "Hier, j'ai mange une pizza.",
          targetEn: 'Yesterday, I ate a pizza.',
          hint: 'Yesterday, I ate...',
        },
        {
          type: 'fill',
          sentence: 'She ___ a book last night.',
          sentenceFr: 'Elle ___ (a lu) un livre hier soir.',
          answer: 'read',
          options: ['reads', 'readed', 'read', 'reading'],
        },
        {
          type: 'mcq',
          question: 'What does "Did you sleep well?" mean?',
          questionFr: 'Que signifie "Did you sleep well?" ?',
          options: [
            'Dors-tu bien ?',
            'Tu as bien dormi ?',
            'Est-ce que tu dors ?',
            'Tu vas dormir ?',
          ],
          correctIndex: 1,
          explanation: '"Did you sleep well?" = As-tu bien dormi ?',
          explanationFr: '"Did you sleep well?" se traduit par "As-tu bien dormi ?".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: "Il n'est pas venu hier.",
          targetEn: "He didn't come yesterday.",
          hint: "He didn't...",
        },
      ],
    },
  },
  {
    level: 'A2' as const,
    theme: 'hobbies',
    order: 23,
    is_premium: false,
    content_json: {
      title: { fr: 'Parler de ses loisirs', en: 'Talking About Hobbies' },
      description: {
        fr: 'Exprimer ses gouts et activites preferees.',
        en: 'Express your tastes and favorite activities.',
      },
      emoji: '\uD83C\uDFB8',
      duration: 8,
      xpReward: 25,
      exercises: [
        {
          type: 'mcq',
          question: 'How do you say "J\'adore cuisiner" in English?',
          questionFr: 'Comment dit-on "J\'adore cuisiner" ?',
          options: ['I hate cooking.', 'I love cooking.', 'I cook love.', 'I am cooking.'],
          correctIndex: 1,
          explanation: '"I love cooking" = J\'adore cuisiner.',
          explanationFr: '"I love cooking" signifie "J\'adore cuisiner".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Je joue de la guitare le week-end.',
          targetEn: 'I play the guitar on weekends.',
          hint: 'I play the guitar...',
        },
        {
          type: 'fill',
          sentence: 'She enjoys ___ in the park.',
          sentenceFr: 'Elle aime ___ (courir) dans le parc.',
          answer: 'running',
          options: ['run', 'runs', 'running', 'ran'],
        },
        {
          type: 'mcq',
          question: 'What does "I\'m keen on photography" mean?',
          questionFr: 'Que signifie "I\'m keen on photography" ?',
          options: ['Je deteste la photo.', 'Je suis passionne de photo.', 'Je fais de la photo.', 'Je vends des photos.'],
          correctIndex: 1,
          explanation: '"Keen on" means passionate about.',
          explanationFr: '"Keen on" signifie "passionne par".',
        },
      ],
    },
  },
  {
    level: 'A2' as const,
    theme: 'transport_directions',
    order: 24,
    is_premium: false,
    content_json: {
      title: { fr: 'Transports & Directions', en: 'Transport & Directions' },
      description: {
        fr: 'Se deplacer et demander son chemin.',
        en: 'Get around and ask for directions.',
      },
      emoji: '\uD83D\uDE8C',
      duration: 9,
      xpReward: 25,
      exercises: [
        {
          type: 'mcq',
          question: 'What does "Turn left at the corner" mean?',
          questionFr: 'Que signifie "Turn left at the corner" ?',
          options: ['Tournez a droite.', 'Allez tout droit.', 'Tournez a gauche au coin.', 'Faites demi-tour.'],
          correctIndex: 2,
          explanation: '"Turn left" = tournez a gauche.',
          explanationFr: '"Turn left at the corner" = tournez a gauche au coin.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Ou est la gare, s\'il vous plait ?',
          targetEn: 'Where is the train station, please?',
          hint: 'Where is the...',
        },
        {
          type: 'fill',
          sentence: 'Go ___ ahead and you\'ll see it on your right.',
          sentenceFr: 'Allez ___ (tout droit) et vous le verrez a votre droite.',
          answer: 'straight',
          options: ['left', 'right', 'straight', 'back'],
        },
        {
          type: 'mcq',
          question: 'Which means of transport goes underground?',
          questionFr: 'Quel transport va sous terre ?',
          options: ['Bus', 'Subway', 'Taxi', 'Bicycle'],
          correctIndex: 1,
          explanation: 'The subway (metro) goes underground.',
          explanationFr: 'Le metro ("subway") va sous terre.',
        },
      ],
    },
  },
  {
    level: 'A2' as const,
    theme: 'health_body',
    order: 25,
    is_premium: false,
    content_json: {
      title: { fr: 'Sante & Corps', en: 'Health & Body' },
      description: {
        fr: 'Decrire des symptomes et aller chez le medecin.',
        en: 'Describe symptoms and visit the doctor.',
      },
      emoji: '\uD83E\uDE7A',
      duration: 8,
      xpReward: 25,
      exercises: [
        {
          type: 'mcq',
          question: 'What does "I have a sore throat" mean?',
          questionFr: 'Que signifie "I have a sore throat" ?',
          options: ['J\'ai mal au ventre.', 'J\'ai mal a la gorge.', 'J\'ai de la fievre.', 'J\'ai mal a la tete.'],
          correctIndex: 1,
          explanation: '"Sore throat" = mal a la gorge.',
          explanationFr: '"A sore throat" signifie "mal a la gorge".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Je dois prendre un medicament.',
          targetEn: 'I need to take medicine.',
          hint: 'I need to take...',
        },
        {
          type: 'fill',
          sentence: 'The doctor said I have a ___.',
          sentenceFr: 'Le docteur a dit que j\'ai un ___ (rhume).',
          answer: 'cold',
          options: ['cold', 'hot', 'warm', 'cool'],
        },
        {
          type: 'mcq',
          question: 'What does "fever" mean?',
          questionFr: 'Que signifie "fever" ?',
          options: ['Rhume', 'Fievre', 'Toux', 'Grippe'],
          correctIndex: 1,
          explanation: '"Fever" means fievre.',
          explanationFr: '"Fever" signifie "fievre".',
        },
      ],
    },
  },
  {
    level: 'A2' as const,
    theme: 'house_furniture',
    order: 26,
    is_premium: true,
    content_json: {
      title: { fr: 'Maison & Meubles', en: 'House & Furniture' },
      description: {
        fr: 'Le vocabulaire des meubles et de la decoration.',
        en: 'Furniture and home decoration vocabulary.',
      },
      emoji: '\uD83D\uDECB\uFE0F',
      duration: 8,
      xpReward: 30,
      exercises: [
        {
          type: 'mcq',
          question: 'Where do you sit to eat dinner?',
          questionFr: 'Ou s\'assoit-on pour diner ?',
          options: ['On the bed', 'On the sofa', 'At the table', 'On the floor'],
          correctIndex: 2,
          explanation: 'We sit at the table to eat dinner.',
          explanationFr: 'On s\'assoit a table ("at the table") pour diner.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Le canape est dans le salon.',
          targetEn: 'The sofa is in the living room.',
          hint: 'The sofa is in...',
        },
        {
          type: 'fill',
          sentence: 'She put the books on the ___.',
          sentenceFr: 'Elle a mis les livres sur l\'___ (etagere).',
          answer: 'shelf',
          options: ['chair', 'shelf', 'bed', 'lamp'],
        },
        {
          type: 'mcq',
          question: 'What is a "wardrobe"?',
          questionFr: 'Qu\'est-ce qu\'une "wardrobe" ?',
          options: ['Un lit', 'Une armoire', 'Un bureau', 'Une table'],
          correctIndex: 1,
          explanation: 'A wardrobe is a piece of furniture for storing clothes.',
          explanationFr: 'Une "wardrobe" est une armoire a vetements.',
        },
      ],
    },
  },
  {
    level: 'A2' as const,
    theme: 'comparatives',
    order: 27,
    is_premium: true,
    content_json: {
      title: { fr: 'Les comparatifs', en: 'Comparatives' },
      description: {
        fr: 'Comparer des personnes et des objets.',
        en: 'Compare people and objects.',
      },
      emoji: '\u2696\uFE0F',
      duration: 9,
      xpReward: 30,
      exercises: [
        {
          type: 'mcq',
          question: 'Which is correct: "more big" or "bigger"?',
          questionFr: 'Lequel est correct : "more big" ou "bigger" ?',
          options: ['More big', 'Bigger', 'Most big', 'Biger'],
          correctIndex: 1,
          explanation: 'Short adjectives add -er: big \u2192 bigger.',
          explanationFr: 'Les adjectifs courts ajoutent -er : big \u2192 bigger.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Paris est plus grand que Lyon.',
          targetEn: 'Paris is bigger than Lyon.',
          hint: 'Paris is ... than Lyon.',
        },
        {
          type: 'fill',
          sentence: 'This book is ___ interesting than that one.',
          sentenceFr: 'Ce livre est ___ (plus) interessant que celui-la.',
          answer: 'more',
          options: ['more', 'most', 'much', 'many'],
        },
        {
          type: 'mcq',
          question: 'What is the comparative of "good"?',
          questionFr: 'Quel est le comparatif de "good" (bon) ?',
          options: ['Gooder', 'More good', 'Better', 'Best'],
          correctIndex: 2,
          explanation: '"Good" is irregular: good \u2192 better \u2192 best.',
          explanationFr: '"Good" est irregulier : good \u2192 better \u2192 best.',
        },
      ],
    },
  },
  {
    level: 'A2' as const,
    theme: 'can_cant',
    order: 28,
    is_premium: true,
    content_json: {
      title: { fr: 'Can & Can\'t', en: 'Can & Can\'t (Abilities)' },
      description: {
        fr: 'Exprimer ce qu\'on sait ou ne sait pas faire.',
        en: 'Express abilities and inabilities.',
      },
      emoji: '\uD83D\uDCAA',
      duration: 8,
      xpReward: 30,
      exercises: [
        {
          type: 'mcq',
          question: 'How do you say "Je sais nager" in English?',
          questionFr: 'Comment dit-on "Je sais nager" ?',
          options: ['I swim.', 'I can swim.', 'I am swimming.', 'I know swim.'],
          correctIndex: 1,
          explanation: '"Can" expresses ability: I can swim.',
          explanationFr: '"Can" exprime la capacite : I can swim = je sais nager.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Elle ne peut pas conduire.',
          targetEn: "She can't drive.",
          hint: "She can't...",
        },
        {
          type: 'fill',
          sentence: '___ you speak French?',
          sentenceFr: '___ (Pouvez)-vous parler francais ?',
          answer: 'Can',
          options: ['Do', 'Can', 'Are', 'Have'],
        },
        {
          type: 'mcq',
          question: 'What does "I can\'t cook" mean?',
          questionFr: 'Que signifie "I can\'t cook" ?',
          options: ['Je cuisine.', 'Je ne sais pas cuisiner.', 'J\'adore cuisiner.', 'Je cuisine bien.'],
          correctIndex: 1,
          explanation: '"Can\'t" = cannot = ne pas savoir / pouvoir.',
          explanationFr: '"I can\'t cook" = je ne sais pas cuisiner.',
        },
      ],
    },
  },
  {
    level: 'A2' as const,
    theme: 'wh_questions',
    order: 29,
    is_premium: true,
    content_json: {
      title: { fr: 'Les questions en WH-', en: 'WH- Questions' },
      description: {
        fr: 'Poser des questions avec who, what, where, when, why, how.',
        en: 'Ask questions with who, what, where, when, why, how.',
      },
      emoji: '\u2753',
      duration: 8,
      xpReward: 30,
      exercises: [
        {
          type: 'mcq',
          question: 'Which word means "ou" (place)?',
          questionFr: 'Quel mot signifie "ou" (lieu) ?',
          options: ['When', 'Why', 'Where', 'What'],
          correctIndex: 2,
          explanation: '"Where" asks about a place.',
          explanationFr: '"Where" sert a demander un lieu.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Pourquoi es-tu en retard ?',
          targetEn: 'Why are you late?',
          hint: 'Why are you...',
        },
        {
          type: 'fill',
          sentence: '___ did you go yesterday?',
          sentenceFr: '___ (Ou) es-tu alle hier ?',
          answer: 'Where',
          options: ['What', 'When', 'Where', 'Who'],
        },
        {
          type: 'mcq',
          question: 'What does "How old are you?" ask about?',
          questionFr: 'Que demande "How old are you?" ?',
          options: ['Le nom', 'L\'age', 'La taille', 'Le poids'],
          correctIndex: 1,
          explanation: '"How old are you?" asks about age.',
          explanationFr: '"How old are you?" demande l\'age.',
        },
      ],
    },
  },
  {
    level: 'A2' as const,
    theme: 'going_to',
    order: 30,
    is_premium: true,
    content_json: {
      title: { fr: 'Le futur avec "going to"', en: 'Going To (Future Plans)' },
      description: {
        fr: 'Exprimer des projets et intentions futures.',
        en: 'Express future plans and intentions.',
      },
      emoji: '\uD83D\uDE80',
      duration: 9,
      xpReward: 30,
      exercises: [
        {
          type: 'mcq',
          question: 'How do you say "Je vais voyager" in English?',
          questionFr: 'Comment dit-on "Je vais voyager" ?',
          options: ['I travel.', 'I going travel.', 'I am going to travel.', 'I will to travel.'],
          correctIndex: 2,
          explanation: '"Going to" expresses future plans: I am going to travel.',
          explanationFr: '"Going to" exprime un projet futur : I am going to travel.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Nous allons demenager le mois prochain.',
          targetEn: 'We are going to move next month.',
          hint: 'We are going to...',
        },
        {
          type: 'fill',
          sentence: 'She ___ going to study medicine.',
          sentenceFr: 'Elle ___ (va) etudier la medecine.',
          answer: 'is',
          options: ['am', 'is', 'are', 'be'],
        },
        {
          type: 'mcq',
          question: 'Which sentence is correct?',
          questionFr: 'Quelle phrase est correcte ?',
          options: [
            'They going to play.',
            'They are going play.',
            'They are going to play.',
            'They go to playing.',
          ],
          correctIndex: 2,
          explanation: 'The correct structure is: subject + be + going to + verb.',
          explanationFr: 'La structure correcte est : sujet + be + going to + verbe.',
        },
      ],
    },
  },

  // ══════════════════════════════════════════════════════════════════
  // B1 — Intermediate (12 lessons, order 31–42)
  // ══════════════════════════════════════════════════════════════════
  {
    level: 'B1' as const,
    theme: 'restaurant',
    order: 31,
    is_premium: false,
    content_json: {
      title: { fr: 'Au restaurant', en: 'At the Restaurant' },
      description: {
        fr: 'Commander, demander la carte et payer.',
        en: 'Order food, ask for the menu, and pay the bill.',
      },
      emoji: '\uD83C\uDF7D\uFE0F',
      duration: 10,
      xpReward: 30,
      exercises: [
        {
          type: 'mcq',
          question: 'How do you ask to see the menu?',
          questionFr: 'Comment demander a voir la carte ?',
          options: [
            'Can I have the bill, please?',
            'Could I see the menu, please?',
            "What is today's special?",
            "I'm ready to order.",
          ],
          correctIndex: 1,
          explanation: '"Could I see the menu?" is the polite way to ask.',
          explanationFr: '"Could I see the menu?" = Puis-je voir la carte ?',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Je suis allergique aux noix.',
          targetEn: 'I am allergic to nuts.',
          hint: 'I am allergic to...',
        },
        {
          type: 'fill',
          sentence: "Could we have the ___, please? We're ready to pay.",
          sentenceFr: "Pourrions-nous avoir ___ (l'addition) ?",
          answer: 'bill',
          options: ['menu', 'bill', 'food', 'table'],
        },
        {
          type: 'mcq',
          question: 'What does "the dish of the day" mean?',
          questionFr: 'Que signifie "the dish of the day" ?',
          options: ['La carte', 'Le dessert', 'Le plat du jour', "L'entree"],
          correctIndex: 2,
          explanation: '"Dish of the day" = le plat du jour.',
          explanationFr: '"Dish of the day" signifie "le plat du jour".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: "Je prendrais le poulet roti, s'il vous plait.",
          targetEn: "I'll have the roast chicken, please.",
          hint: "I'll have the...",
        },
      ],
    },
  },
  {
    level: 'B1' as const,
    theme: 'travel_airports',
    order: 32,
    is_premium: false,
    content_json: {
      title: { fr: 'Voyages & Aeroports', en: 'Travel & Airports' },
      description: {
        fr: 'Vocabulaire essentiel pour voyager.',
        en: 'Essential vocabulary for travelling.',
      },
      emoji: '\u2708\uFE0F',
      duration: 10,
      xpReward: 30,
      exercises: [
        {
          type: 'mcq',
          question: 'Where do you check in your luggage?',
          questionFr: 'Ou enregistre-t-on ses bagages ?',
          options: ['At the gate', 'At the check-in desk', 'At security', 'On the plane'],
          correctIndex: 1,
          explanation: 'You check in at the check-in desk.',
          explanationFr: 'On enregistre ses bagages au comptoir d\'enregistrement.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Mon vol est retarde de deux heures.',
          targetEn: 'My flight is delayed by two hours.',
          hint: 'My flight is delayed by...',
        },
        {
          type: 'fill',
          sentence: 'Please have your ___ ready at the gate.',
          sentenceFr: "Veuillez avoir votre ___ (carte d'embarquement) prete.",
          answer: 'boarding pass',
          options: ['luggage', 'passport', 'boarding pass', 'ticket'],
        },
        {
          type: 'mcq',
          question: 'What does "overhead bin" mean?',
          questionFr: 'Que signifie "overhead bin" ?',
          options: [
            'Le couloir',
            'Le compartiment a bagages au-dessus',
            'Le siege fenetre',
            'La sortie de secours',
          ],
          correctIndex: 1,
          explanation: '"Overhead bin" is the storage above your seat.',
          explanationFr: '"Overhead bin" = le compartiment a bagages au-dessus du siege.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Y a-t-il une correspondance a Londres ?',
          targetEn: 'Is there a connection in London?',
          hint: 'Is there a connection in...',
        },
      ],
    },
  },
  {
    level: 'B1' as const,
    theme: 'job_interviews',
    order: 33,
    is_premium: false,
    content_json: {
      title: { fr: "Entretiens d'embauche", en: 'Job Interviews' },
      description: {
        fr: "Reussir un entretien d'embauche en anglais.",
        en: 'Succeed in a job interview in English.',
      },
      emoji: '\uD83D\uDCBC',
      duration: 10,
      xpReward: 30,
      exercises: [
        {
          type: 'mcq',
          question: 'What does "What are your strengths?" mean?',
          questionFr: 'Que signifie "What are your strengths?" ?',
          options: [
            'Quelles sont vos faiblesses ?',
            'Quelles sont vos qualites / points forts ?',
            'Quelle est votre experience ?',
            'Pourquoi postulez-vous ?',
          ],
          correctIndex: 1,
          explanation: '"Strengths" are qualities or strong points.',
          explanationFr: '"Strengths" = points forts, qualites.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: "J'ai cinq ans d'experience dans ce domaine.",
          targetEn: 'I have five years of experience in this field.',
          hint: 'I have ... years of experience in...',
        },
        {
          type: 'fill',
          sentence: 'I am very ___ in this position.',
          sentenceFr: 'Je suis tres ___ (interesse) par ce poste.',
          answer: 'interested',
          options: ['excited', 'interested', 'happy', 'working'],
        },
        {
          type: 'mcq',
          question: 'What does "Could you tell me about your background?" mean?',
          questionFr: 'Que signifie "Could you tell me about your background?" ?',
          options: [
            "Parlez-moi de votre pays d'origine.",
            'Pouvez-vous me parler de votre parcours ?',
            'Quel est votre diplome ?',
            'Pourquoi avez-vous quitte votre dernier emploi ?',
          ],
          correctIndex: 1,
          explanation: '"Background" refers to your professional experience.',
          explanationFr: '"Background" designe ici votre parcours professionnel.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Je travaille bien en equipe.',
          targetEn: 'I work well in a team.',
          hint: 'I work well in...',
        },
      ],
    },
  },
  {
    level: 'B1' as const,
    theme: 'present_perfect',
    order: 34,
    is_premium: false,
    content_json: {
      title: { fr: 'Le present perfect', en: 'Present Perfect' },
      description: {
        fr: 'Parler d\'experiences et d\'actions recentes.',
        en: 'Talk about experiences and recent actions.',
      },
      emoji: '\u2705',
      duration: 10,
      xpReward: 35,
      exercises: [
        {
          type: 'mcq',
          question: 'Which sentence uses the present perfect correctly?',
          questionFr: 'Quelle phrase utilise le present perfect correctement ?',
          options: [
            'I have went to Paris.',
            'I have been to Paris.',
            'I have go to Paris.',
            'I was been to Paris.',
          ],
          correctIndex: 1,
          explanation: 'Present perfect: have/has + past participle. "Been" is the participle of "be/go".',
          explanationFr: 'Present perfect : have/has + participe passe. "Been" est le participe de "be/go".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'J\'ai deja visite Londres.',
          targetEn: 'I have already visited London.',
          hint: 'I have already...',
        },
        {
          type: 'fill',
          sentence: 'She has ___ lived in three countries.',
          sentenceFr: 'Elle ___ (a) vecu dans trois pays.',
          answer: 'already',
          options: ['yet', 'already', 'never', 'just'],
        },
        {
          type: 'mcq',
          question: 'When do we use "yet" in present perfect?',
          questionFr: 'Quand utilise-t-on "yet" au present perfect ?',
          options: [
            'In affirmative sentences',
            'In negative sentences and questions',
            'Only in questions',
            'Never with present perfect',
          ],
          correctIndex: 1,
          explanation: '"Yet" is used in negatives and questions.',
          explanationFr: '"Yet" s\'utilise dans les phrases negatives et les questions.',
        },
      ],
    },
  },
  {
    level: 'B1' as const,
    theme: 'conditionals',
    order: 35,
    is_premium: false,
    content_json: {
      title: { fr: 'Les conditionnels (1er & 2e)', en: 'Conditionals (1st & 2nd)' },
      description: {
        fr: 'Exprimer des conditions et des hypotheses.',
        en: 'Express conditions and hypothetical situations.',
      },
      emoji: '\uD83E\uDD14',
      duration: 10,
      xpReward: 35,
      exercises: [
        {
          type: 'mcq',
          question: 'Which sentence is a first conditional?',
          questionFr: 'Quelle phrase est un premier conditionnel ?',
          options: [
            'If I won the lottery, I would buy a house.',
            'If it rains, I will take an umbrella.',
            'If I were you, I would study more.',
            'If I had known, I would have come.',
          ],
          correctIndex: 1,
          explanation: '1st conditional: If + present, will + verb.',
          explanationFr: '1er conditionnel : If + present, will + verbe.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Si j\'etais riche, je voyagerais partout.',
          targetEn: 'If I were rich, I would travel everywhere.',
          hint: 'If I were rich, I would...',
        },
        {
          type: 'fill',
          sentence: 'If she ___ harder, she would pass the exam.',
          sentenceFr: 'Si elle ___ (etudiait) plus, elle reussirait l\'examen.',
          answer: 'studied',
          options: ['studies', 'studied', 'study', 'will study'],
        },
        {
          type: 'mcq',
          question: 'What structure does the second conditional use?',
          questionFr: 'Quelle structure utilise le deuxieme conditionnel ?',
          options: [
            'If + present, will + verb',
            'If + past simple, would + verb',
            'If + past perfect, would have + verb',
            'If + future, will + verb',
          ],
          correctIndex: 1,
          explanation: '2nd conditional: If + past simple, would + verb.',
          explanationFr: '2e conditionnel : If + passe simple, would + verbe.',
        },
      ],
    },
  },
  {
    level: 'B1' as const,
    theme: 'expressing_opinions',
    order: 36,
    is_premium: false,
    content_json: {
      title: { fr: 'Exprimer son opinion', en: 'Expressing Opinions' },
      description: {
        fr: 'Donner et defendre son avis en anglais.',
        en: 'Give and defend your opinion in English.',
      },
      emoji: '\uD83D\uDDE3\uFE0F',
      duration: 9,
      xpReward: 30,
      exercises: [
        {
          type: 'mcq',
          question: 'Which phrase is used to give an opinion?',
          questionFr: 'Quelle expression sert a donner un avis ?',
          options: [
            'According to the book...',
            'In my opinion...',
            'It is a fact that...',
            'As we know...',
          ],
          correctIndex: 1,
          explanation: '"In my opinion" introduces a personal view.',
          explanationFr: '"In my opinion" introduit un avis personnel.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Je pense que les reseaux sociaux sont utiles.',
          targetEn: 'I think social media is useful.',
          hint: 'I think...',
        },
        {
          type: 'fill',
          sentence: 'I ___ agree with that statement.',
          sentenceFr: 'Je ne suis ___ (pas) d\'accord avec cette affirmation.',
          answer: "don't",
          options: ['not', "don't", "can't", "won't"],
        },
        {
          type: 'mcq',
          question: 'What does "I strongly believe" express?',
          questionFr: 'Qu\'exprime "I strongly believe" ?',
          options: ['Un doute', 'Une certitude forte', 'Un desaccord', 'Une question'],
          correctIndex: 1,
          explanation: '"I strongly believe" = je crois fermement.',
          explanationFr: '"I strongly believe" exprime une conviction forte.',
        },
      ],
    },
  },
  {
    level: 'B1' as const,
    theme: 'environment',
    order: 37,
    is_premium: false,
    content_json: {
      title: { fr: 'L\'environnement', en: 'The Environment' },
      description: {
        fr: 'Parler de l\'ecologie et du changement climatique.',
        en: 'Talk about ecology and climate change.',
      },
      emoji: '\uD83C\uDF0D',
      duration: 10,
      xpReward: 30,
      exercises: [
        {
          type: 'mcq',
          question: 'What does "renewable energy" mean?',
          questionFr: 'Que signifie "renewable energy" ?',
          options: ['Energie nucleaire', 'Energie renouvelable', 'Energie fossile', 'Energie solaire uniquement'],
          correctIndex: 1,
          explanation: '"Renewable energy" = energie renouvelable (solar, wind, etc.).',
          explanationFr: '"Renewable energy" = energie renouvelable (solaire, eolienne, etc.).',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Nous devons reduire notre consommation d\'energie.',
          targetEn: 'We must reduce our energy consumption.',
          hint: 'We must reduce...',
        },
        {
          type: 'fill',
          sentence: 'We should ___ more to protect the environment.',
          sentenceFr: 'Nous devrions ___ (recycler) plus pour proteger l\'environnement.',
          answer: 'recycle',
          options: ['pollute', 'recycle', 'waste', 'burn'],
        },
        {
          type: 'mcq',
          question: 'What is "global warming"?',
          questionFr: 'Qu\'est-ce que le "global warming" ?',
          options: ['La pollution', 'Le rechauffement climatique', 'La deforestation', 'L\'extinction'],
          correctIndex: 1,
          explanation: '"Global warming" = le rechauffement climatique.',
          explanationFr: '"Global warming" signifie "le rechauffement climatique".',
        },
      ],
    },
  },
  {
    level: 'B1' as const,
    theme: 'technology',
    order: 38,
    is_premium: false,
    content_json: {
      title: { fr: 'La technologie', en: 'Technology' },
      description: {
        fr: 'Vocabulaire de la technologie et du numerique.',
        en: 'Technology and digital vocabulary.',
      },
      emoji: '\uD83D\uDCBB',
      duration: 9,
      xpReward: 30,
      exercises: [
        {
          type: 'mcq',
          question: 'What does "to download" mean?',
          questionFr: 'Que signifie "to download" ?',
          options: ['Envoyer', 'Telecharger', 'Supprimer', 'Partager'],
          correctIndex: 1,
          explanation: '"To download" = telecharger (vers son appareil).',
          explanationFr: '"To download" signifie "telecharger".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'J\'ai oublie mon mot de passe.',
          targetEn: 'I forgot my password.',
          hint: 'I forgot my...',
        },
        {
          type: 'fill',
          sentence: 'You need to ___ the app to get the latest features.',
          sentenceFr: 'Vous devez ___ (mettre a jour) l\'appli pour les dernieres fonctionnalites.',
          answer: 'update',
          options: ['delete', 'update', 'install', 'close'],
        },
        {
          type: 'mcq',
          question: 'What is a "browser"?',
          questionFr: 'Qu\'est-ce qu\'un "browser" ?',
          options: ['Un reseau social', 'Un moteur de recherche', 'Un navigateur web', 'Un antivirus'],
          correctIndex: 2,
          explanation: 'A browser is software for accessing websites (Chrome, Firefox...).',
          explanationFr: 'Un "browser" est un navigateur web (Chrome, Firefox...).',
        },
      ],
    },
  },
  {
    level: 'B1' as const,
    theme: 'reported_speech',
    order: 39,
    is_premium: true,
    content_json: {
      title: { fr: 'Le discours indirect', en: 'Reported Speech' },
      description: {
        fr: 'Rapporter ce que quelqu\'un a dit.',
        en: 'Report what someone said.',
      },
      emoji: '\uD83D\uDCAC',
      duration: 10,
      xpReward: 35,
      exercises: [
        {
          type: 'mcq',
          question: 'Convert to reported speech: "I am happy."',
          questionFr: 'Mettez au discours indirect : "I am happy."',
          options: [
            'She said she is happy.',
            'She said she was happy.',
            'She said she were happy.',
            'She said she be happy.',
          ],
          correctIndex: 1,
          explanation: 'In reported speech, present becomes past: am \u2192 was.',
          explanationFr: 'Au discours indirect, le present devient passe : am \u2192 was.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Il a dit qu\'il viendrait demain.',
          targetEn: 'He said he would come tomorrow.',
          hint: 'He said he would...',
        },
        {
          type: 'fill',
          sentence: 'She told me she ___ been to Japan.',
          sentenceFr: 'Elle m\'a dit qu\'elle ___ (avait) ete au Japon.',
          answer: 'had',
          options: ['has', 'had', 'have', 'was'],
        },
        {
          type: 'mcq',
          question: 'In reported speech, "will" becomes:',
          questionFr: 'Au discours indirect, "will" devient :',
          options: ['shall', 'would', 'will', 'could'],
          correctIndex: 1,
          explanation: '"Will" becomes "would" in reported speech.',
          explanationFr: '"Will" devient "would" au discours indirect.',
        },
      ],
    },
  },
  {
    level: 'B1' as const,
    theme: 'passive_voice',
    order: 40,
    is_premium: true,
    content_json: {
      title: { fr: 'La voix passive', en: 'Passive Voice' },
      description: {
        fr: 'Construire et utiliser la voix passive.',
        en: 'Build and use the passive voice.',
      },
      emoji: '\uD83D\uDD04',
      duration: 10,
      xpReward: 35,
      exercises: [
        {
          type: 'mcq',
          question: 'Which sentence is in the passive voice?',
          questionFr: 'Quelle phrase est a la voix passive ?',
          options: [
            'The cat ate the fish.',
            'The fish was eaten by the cat.',
            'The cat is eating.',
            'The cat will eat.',
          ],
          correctIndex: 1,
          explanation: 'Passive: subject receives the action (be + past participle).',
          explanationFr: 'Passif : le sujet subit l\'action (be + participe passe).',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Ce livre a ete ecrit par un auteur celebre.',
          targetEn: 'This book was written by a famous author.',
          hint: 'This book was written by...',
        },
        {
          type: 'fill',
          sentence: 'The window ___ broken by the ball.',
          sentenceFr: 'La fenetre ___ (a ete) cassee par le ballon.',
          answer: 'was',
          options: ['is', 'was', 'were', 'been'],
        },
        {
          type: 'mcq',
          question: 'How do we form the passive voice?',
          questionFr: 'Comment forme-t-on la voix passive ?',
          options: [
            'Subject + verb + object',
            'Subject + be + past participle',
            'Subject + have + verb',
            'Subject + do + verb',
          ],
          correctIndex: 1,
          explanation: 'Passive = subject + be + past participle.',
          explanationFr: 'Passif = sujet + be + participe passe.',
        },
      ],
    },
  },
  {
    level: 'B1' as const,
    theme: 'business_english',
    order: 41,
    is_premium: true,
    content_json: {
      title: { fr: 'Anglais professionnel', en: 'Business English' },
      description: {
        fr: 'Les bases de l\'anglais en milieu professionnel.',
        en: 'The basics of English in a professional setting.',
      },
      emoji: '\uD83D\uDCC8',
      duration: 10,
      xpReward: 35,
      exercises: [
        {
          type: 'mcq',
          question: 'How do you start a formal email?',
          questionFr: 'Comment commence-t-on un e-mail formel ?',
          options: ['Hey!', 'Dear Sir/Madam,', 'What\'s up?', 'Yo,'],
          correctIndex: 1,
          explanation: '"Dear Sir/Madam" is the standard formal opening.',
          explanationFr: '"Dear Sir/Madam" est l\'ouverture formelle standard.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Veuillez trouver ci-joint mon CV.',
          targetEn: 'Please find attached my CV.',
          hint: 'Please find attached...',
        },
        {
          type: 'fill',
          sentence: 'I look forward to ___ from you.',
          sentenceFr: 'J\'ai hate de ___ (recevoir) de vos nouvelles.',
          answer: 'hearing',
          options: ['hear', 'heard', 'hearing', 'hears'],
        },
        {
          type: 'mcq',
          question: 'What does "deadline" mean?',
          questionFr: 'Que signifie "deadline" ?',
          options: ['Reunion', 'Date limite', 'Salaire', 'Conge'],
          correctIndex: 1,
          explanation: '"Deadline" = date limite pour rendre un travail.',
          explanationFr: '"Deadline" signifie "date limite".',
        },
      ],
    },
  },
  {
    level: 'B1' as const,
    theme: 'culture_traditions',
    order: 42,
    is_premium: true,
    content_json: {
      title: { fr: 'Culture & Traditions', en: 'Culture & Traditions' },
      description: {
        fr: 'Decouvrir les cultures anglophones.',
        en: 'Discover English-speaking cultures.',
      },
      emoji: '\uD83C\uDF8A',
      duration: 9,
      xpReward: 35,
      exercises: [
        {
          type: 'mcq',
          question: 'What is "Thanksgiving"?',
          questionFr: 'Qu\'est-ce que "Thanksgiving" ?',
          options: [
            'Une fete anglaise',
            'Une fete americaine d\'action de grace',
            'Un jour ferie australien',
            'Une fete religieuse',
          ],
          correctIndex: 1,
          explanation: 'Thanksgiving is an American holiday celebrated in November.',
          explanationFr: 'Thanksgiving est une fete americaine celebree en novembre.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Les Britanniques boivent beaucoup de the.',
          targetEn: 'British people drink a lot of tea.',
          hint: 'British people drink...',
        },
        {
          type: 'fill',
          sentence: 'In the UK, people drive on the ___ side of the road.',
          sentenceFr: 'Au Royaume-Uni, on conduit du cote ___ (gauche).',
          answer: 'left',
          options: ['right', 'left', 'middle', 'wrong'],
        },
        {
          type: 'mcq',
          question: 'What is "Boxing Day"?',
          questionFr: 'Qu\'est-ce que "Boxing Day" ?',
          options: [
            'Un jour de boxe',
            'Le lendemain de Noel (26 decembre)',
            'La veille de Noel',
            'Le jour de l\'an',
          ],
          correctIndex: 1,
          explanation: 'Boxing Day is December 26th, a public holiday in the UK.',
          explanationFr: 'Boxing Day est le 26 decembre, un jour ferie au Royaume-Uni.',
        },
      ],
    },
  },

  // ══════════════════════════════════════════════════════════════════
  // B2 — Upper Intermediate (8 lessons, order 43–50)
  // ══════════════════════════════════════════════════════════════════
  {
    level: 'B2' as const,
    theme: 'advanced_conditionals',
    order: 43,
    is_premium: false,
    content_json: {
      title: { fr: 'Conditionnels avances', en: 'Advanced Conditionals' },
      description: {
        fr: 'Maitriser le 3e conditionnel et les conditionnels mixtes.',
        en: 'Master the 3rd conditional and mixed conditionals.',
      },
      emoji: '\uD83C\uDF00',
      duration: 12,
      xpReward: 40,
      exercises: [
        {
          type: 'mcq',
          question: 'Which is a third conditional sentence?',
          questionFr: 'Quelle phrase est un troisieme conditionnel ?',
          options: [
            'If I study, I will pass.',
            'If I studied, I would pass.',
            'If I had studied, I would have passed.',
            'If I study, I pass.',
          ],
          correctIndex: 2,
          explanation: '3rd conditional: If + past perfect, would have + past participle.',
          explanationFr: '3e conditionnel : If + plus-que-parfait, would have + participe passe.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Si j\'avais su, je serais venu plus tot.',
          targetEn: 'If I had known, I would have come earlier.',
          hint: 'If I had known, I would have...',
        },
        {
          type: 'fill',
          sentence: 'If she ___ the email, she would have replied.',
          sentenceFr: 'Si elle ___ (avait vu) l\'e-mail, elle aurait repondu.',
          answer: 'had seen',
          options: ['saw', 'had seen', 'has seen', 'would see'],
        },
        {
          type: 'mcq',
          question: 'What is a mixed conditional?',
          questionFr: 'Qu\'est-ce qu\'un conditionnel mixte ?',
          options: [
            'A condition using only the present tense.',
            'A condition that mixes tenses from different conditional types.',
            'A condition with two subjects.',
            'A condition that uses "unless".',
          ],
          correctIndex: 1,
          explanation: 'Mixed conditionals combine elements from different conditional types.',
          explanationFr: 'Les conditionnels mixtes combinent des elements de differents types.',
        },
      ],
    },
  },
  {
    level: 'B2' as const,
    theme: 'debating_argumentation',
    order: 44,
    is_premium: false,
    content_json: {
      title: { fr: 'Debat & Argumentation', en: 'Debating & Argumentation' },
      description: {
        fr: 'Structurer un argument et debattre.',
        en: 'Structure an argument and debate effectively.',
      },
      emoji: '\u2696\uFE0F',
      duration: 12,
      xpReward: 40,
      exercises: [
        {
          type: 'mcq',
          question: 'Which phrase introduces a counterargument?',
          questionFr: 'Quelle expression introduit un contre-argument ?',
          options: [
            'I totally agree.',
            'On the other hand...',
            'In conclusion...',
            'First of all...',
          ],
          correctIndex: 1,
          explanation: '"On the other hand" introduces an opposing viewpoint.',
          explanationFr: '"On the other hand" introduit un point de vue oppose.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Il y a des arguments pour et contre.',
          targetEn: 'There are arguments for and against.',
          hint: 'There are arguments...',
        },
        {
          type: 'fill',
          sentence: '___, I would like to point out that this is not the only solution.',
          sentenceFr: '___ (Cependant), je voudrais souligner que ce n\'est pas la seule solution.',
          answer: 'However',
          options: ['Therefore', 'However', 'Moreover', 'Finally'],
        },
        {
          type: 'mcq',
          question: 'What does "I see your point, but..." express?',
          questionFr: 'Qu\'exprime "I see your point, but..." ?',
          options: [
            'Un accord total',
            'Un desaccord partiel (poli)',
            'Une question',
            'Une conclusion',
          ],
          correctIndex: 1,
          explanation: '"I see your point, but..." = polite partial disagreement.',
          explanationFr: '"I see your point, but..." = un desaccord partiel poli.',
        },
      ],
    },
  },
  {
    level: 'B2' as const,
    theme: 'media_journalism',
    order: 45,
    is_premium: false,
    content_json: {
      title: { fr: 'Medias & Journalisme', en: 'Media & Journalism' },
      description: {
        fr: 'Comprendre et discuter les medias en anglais.',
        en: 'Understand and discuss media in English.',
      },
      emoji: '\uD83D\uDCF0',
      duration: 11,
      xpReward: 40,
      exercises: [
        {
          type: 'mcq',
          question: 'What does "breaking news" mean?',
          questionFr: 'Que signifie "breaking news" ?',
          options: ['De fausses nouvelles', 'Des informations de derniere minute', 'Un journal', 'Une interview'],
          correctIndex: 1,
          explanation: '"Breaking news" = news that is happening right now.',
          explanationFr: '"Breaking news" = informations de derniere minute.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Les reseaux sociaux influencent l\'opinion publique.',
          targetEn: 'Social media influences public opinion.',
          hint: 'Social media influences...',
        },
        {
          type: 'fill',
          sentence: 'The journalist wrote an ___ about climate change.',
          sentenceFr: 'Le journaliste a ecrit un ___ (article) sur le changement climatique.',
          answer: 'article',
          options: ['essay', 'article', 'book', 'letter'],
        },
        {
          type: 'mcq',
          question: 'What is "fake news"?',
          questionFr: 'Qu\'est-ce que les "fake news" ?',
          options: [
            'Des nouvelles amusantes',
            'De fausses informations diffusees deliberement',
            'Des nouvelles sportives',
            'Des rumeurs entre amis',
          ],
          correctIndex: 1,
          explanation: '"Fake news" is deliberately false information.',
          explanationFr: '"Fake news" = fausses informations diffusees deliberement.',
        },
      ],
    },
  },
  {
    level: 'B2' as const,
    theme: 'phrasal_verbs_context',
    order: 46,
    is_premium: false,
    content_json: {
      title: { fr: 'Phrasal Verbs en contexte', en: 'Phrasal Verbs in Context' },
      description: {
        fr: 'Maitriser les phrasal verbs les plus utiles.',
        en: 'Master the most useful phrasal verbs.',
      },
      emoji: '\uD83D\uDD17',
      duration: 11,
      xpReward: 40,
      exercises: [
        {
          type: 'mcq',
          question: 'What does "give up" mean?',
          questionFr: 'Que signifie "give up" ?',
          options: ['Donner', 'Abandonner', 'Se lever', 'Offrir'],
          correctIndex: 1,
          explanation: '"Give up" = abandonner, renoncer.',
          explanationFr: '"Give up" signifie "abandonner".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Je m\'entends bien avec mes collegues.',
          targetEn: 'I get along well with my colleagues.',
          hint: 'I get along...',
        },
        {
          type: 'fill',
          sentence: 'Can you ___ out what this word means?',
          sentenceFr: 'Peux-tu ___ (decouvrir) ce que ce mot signifie ?',
          answer: 'figure',
          options: ['find', 'figure', 'make', 'work'],
        },
        {
          type: 'mcq',
          question: 'What does "look forward to" mean?',
          questionFr: 'Que signifie "look forward to" ?',
          options: ['Regarder en avant', 'Avoir hate de', 'Se retourner', 'Chercher'],
          correctIndex: 1,
          explanation: '"Look forward to" = avoir hate de, attendre avec impatience.',
          explanationFr: '"Look forward to" = avoir hate de.',
        },
      ],
    },
  },
  {
    level: 'B2' as const,
    theme: 'academic_writing',
    order: 47,
    is_premium: false,
    content_json: {
      title: { fr: 'Ecriture academique', en: 'Academic Writing' },
      description: {
        fr: 'Les bases de l\'ecriture academique en anglais.',
        en: 'The basics of academic writing in English.',
      },
      emoji: '\uD83C\uDF93',
      duration: 12,
      xpReward: 40,
      exercises: [
        {
          type: 'mcq',
          question: 'Which phrase is appropriate for academic writing?',
          questionFr: 'Quelle expression convient a l\'ecriture academique ?',
          options: [
            'I think it\'s cool.',
            'This essay will examine...',
            'So basically...',
            'Stuff like that.',
          ],
          correctIndex: 1,
          explanation: '"This essay will examine..." is formal and academic.',
          explanationFr: '"This essay will examine..." est formel et academique.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'En conclusion, les resultats montrent que...',
          targetEn: 'In conclusion, the results show that...',
          hint: 'In conclusion, the results...',
        },
        {
          type: 'fill',
          sentence: '___ to recent studies, exercise improves mental health.',
          sentenceFr: '___ (Selon) des etudes recentes, l\'exercice ameliore la sante mentale.',
          answer: 'According',
          options: ['Thanks', 'According', 'Due', 'Related'],
        },
        {
          type: 'mcq',
          question: 'What does "furthermore" mean?',
          questionFr: 'Que signifie "furthermore" ?',
          options: ['Cependant', 'De plus', 'En conclusion', 'Par consequent'],
          correctIndex: 1,
          explanation: '"Furthermore" = de plus, en outre.',
          explanationFr: '"Furthermore" signifie "de plus" ou "en outre".',
        },
      ],
    },
  },
  {
    level: 'B2' as const,
    theme: 'idiomatic_expressions',
    order: 48,
    is_premium: true,
    content_json: {
      title: { fr: 'Expressions idiomatiques', en: 'Idiomatic Expressions' },
      description: {
        fr: 'Comprendre et utiliser les expressions anglaises courantes.',
        en: 'Understand and use common English idioms.',
      },
      emoji: '\uD83D\uDCA1',
      duration: 10,
      xpReward: 40,
      exercises: [
        {
          type: 'mcq',
          question: 'What does "It\'s raining cats and dogs" mean?',
          questionFr: 'Que signifie "It\'s raining cats and dogs" ?',
          options: [
            'Des animaux tombent du ciel.',
            'Il pleut tres fort.',
            'Il fait beau.',
            'Il y a des animaux dehors.',
          ],
          correctIndex: 1,
          explanation: '"Raining cats and dogs" = il pleut a verse.',
          explanationFr: 'Cette expression signifie "il pleut a verse".',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'Il a mis les pieds dans le plat.',
          targetEn: 'He put his foot in his mouth.',
          hint: 'He put his foot...',
        },
        {
          type: 'fill',
          sentence: 'That exam was a piece of ___.',
          sentenceFr: 'Cet examen etait un jeu d\'___ (enfant) / tres facile.',
          answer: 'cake',
          options: ['pie', 'cake', 'bread', 'candy'],
        },
        {
          type: 'mcq',
          question: 'What does "break the ice" mean?',
          questionFr: 'Que signifie "break the ice" ?',
          options: ['Casser de la glace', 'Detendre l\'atmosphere', 'Faire froid', 'Commencer a manger'],
          correctIndex: 1,
          explanation: '"Break the ice" = start a conversation, ease tension.',
          explanationFr: '"Break the ice" = detendre l\'atmosphere, briser la glace.',
        },
      ],
    },
  },
  {
    level: 'B2' as const,
    theme: 'advanced_passive_causative',
    order: 49,
    is_premium: true,
    content_json: {
      title: { fr: 'Passif avance & Causatif', en: 'Advanced Passive & Causative' },
      description: {
        fr: 'Structures passives complexes et forme causative.',
        en: 'Complex passive structures and causative form.',
      },
      emoji: '\uD83D\uDD27',
      duration: 12,
      xpReward: 45,
      exercises: [
        {
          type: 'mcq',
          question: 'Which sentence uses the causative correctly?',
          questionFr: 'Quelle phrase utilise le causatif correctement ?',
          options: [
            'I cut my hair.',
            'I had my hair cut.',
            'I had cut my hair.',
            'My hair is cutting.',
          ],
          correctIndex: 1,
          explanation: 'Causative: have + object + past participle (someone else does it).',
          explanationFr: 'Causatif : have + objet + participe passe (quelqu\'un d\'autre le fait).',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into English.',
          instructionFr: 'Traduisez en anglais.',
          sourceFr: 'J\'ai fait reparer ma voiture.',
          targetEn: 'I had my car repaired.',
          hint: 'I had my car...',
        },
        {
          type: 'fill',
          sentence: 'The report is believed ___ be inaccurate.',
          sentenceFr: 'Le rapport est considere comme ___ (etant) inexact.',
          answer: 'to',
          options: ['to', 'for', 'as', 'by'],
        },
        {
          type: 'mcq',
          question: 'What does "get something done" imply?',
          questionFr: 'Qu\'implique "get something done" ?',
          options: [
            'Faire soi-meme',
            'Faire faire par quelqu\'un d\'autre',
            'Ne rien faire',
            'Commencer quelque chose',
          ],
          correctIndex: 1,
          explanation: '"Get something done" = have someone else do it.',
          explanationFr: '"Get something done" = faire faire par quelqu\'un d\'autre.',
        },
      ],
    },
  },
  {
    level: 'B2' as const,
    theme: 'formal_vs_informal_register',
    order: 50,
    is_premium: true,
    content_json: {
      title: { fr: 'Registre formel vs informel', en: 'Formal vs Informal Register' },
      description: {
        fr: 'Adapter son langage au contexte.',
        en: 'Adapt your language to the context.',
      },
      emoji: '\uD83C\uDFA9',
      duration: 11,
      xpReward: 45,
      exercises: [
        {
          type: 'mcq',
          question: 'Which is more formal?',
          questionFr: 'Quelle expression est plus formelle ?',
          options: [
            'Hey, what\'s up?',
            'Good morning, how do you do?',
            'Yo, how\'s it going?',
            'Hi there!',
          ],
          correctIndex: 1,
          explanation: '"Good morning, how do you do?" is very formal.',
          explanationFr: '"Good morning, how do you do?" est tres formel.',
        },
        {
          type: 'translation',
          instructionEn: 'Translate into formal English.',
          instructionFr: 'Traduisez en anglais formel.',
          sourceFr: 'Je vous serais reconnaissant de bien vouloir repondre.',
          targetEn: 'I would be grateful if you could reply.',
          hint: 'I would be grateful if...',
        },
        {
          type: 'fill',
          sentence: 'I am writing to ___ about the recent incident.',
          sentenceFr: 'Je vous ecris pour ___ (me plaindre) de l\'incident recent.',
          answer: 'complain',
          options: ['talk', 'complain', 'chat', 'say'],
        },
        {
          type: 'mcq',
          question: 'Which is the informal version of "I would like to request..."?',
          questionFr: 'Quelle est la version informelle de "I would like to request..." ?',
          options: [
            'I hereby request...',
            'Could I possibly ask for...',
            'Can I have...?',
            'I wish to formally petition...',
          ],
          correctIndex: 2,
          explanation: '"Can I have...?" is the casual, informal equivalent.',
          explanationFr: '"Can I have...?" est l\'equivalent decontracte et informel.',
        },
      ],
    },
  },
];

export async function seedLessons(client: PrismaClient) {
  // Always delete and recreate to prevent duplicates
  await client.lesson.deleteMany({});
  console.log('Seeding lessons...');
  for (const lesson of lessons) {
    await client.lesson.create({ data: lesson });
  }
  console.log(`Seeded ${lessons.length} lessons successfully.`);
}

